import type { CharacterCategory } from "./character-symbols";

type ExtraEntry = { char: string; category: CharacterCategory; tags: string[] };

/** Additional symbols (merged into CHARACTER_ENTRIES). */
export const EXTRA_CHARACTER_ENTRIES: ExtraEntry[] = [
  // —— More currency ——
  { char: "元", category: "currency", tags: ["yuan", "cny", "يوان"] },
  { char: "₡", category: "currency", tags: ["colon", "crc"] },
  { char: "₲", category: "currency", tags: ["guarani"] },
  { char: "₵", category: "currency", tags: ["cedi", "ghana"] },
  { char: "₸", category: "currency", tags: ["tenge", "kazakhstan"] },
  { char: "₼", category: "currency", tags: ["manat", "azerbaijan"] },
  { char: "₺", category: "currency", tags: ["lira", "turkish", "ليرة"] },
  { char: "₭", category: "currency", tags: ["kip", "laos"] },

  // —— More arrows ——
  { char: "⇄", category: "arrows", tags: ["swap", "exchange", "تبادل", "سهم"] },
  { char: "⇆", category: "arrows", tags: ["left right", "سهم"] },
  { char: "⇅", category: "arrows", tags: ["up down", "سهم"] },
  { char: "⇈", category: "arrows", tags: ["up pair", "سهم"] },
  { char: "⇊", category: "arrows", tags: ["down pair", "سهم"] },
  { char: "↷", category: "arrows", tags: ["clockwise", "سهم"] },
  { char: "↶", category: "arrows", tags: ["counter", "سهم"] },
  { char: "↺", category: "arrows", tags: ["undo", "سهم"] },
  { char: "↻", category: "arrows", tags: ["redo", "سهم"] },
  { char: "⤴", category: "arrows", tags: ["curve up", "سهم"] },
  { char: "⤵", category: "arrows", tags: ["curve down", "سهم"] },
  { char: "⟷", category: "arrows", tags: ["long both", "سهم"] },
  { char: "⟸", category: "arrows", tags: ["double left", "سهم"] },
  { char: "⟹", category: "arrows", tags: ["double right", "سهم"] },
  { char: "⟺", category: "arrows", tags: ["double both", "سهم"] },
  { char: "↦", category: "arrows", tags: ["maps to", "سهم"] },
  { char: "↤", category: "arrows", tags: ["from", "سهم"] },
  { char: "⇠", category: "arrows", tags: ["dashed left", "سهم"] },
  { char: "⇢", category: "arrows", tags: ["dashed right", "سهم"] },
  { char: "⇧", category: "arrows", tags: ["shift", "up", "سهم"] },
  { char: "⇩", category: "arrows", tags: ["down", "سهم"] },
  { char: "⮕", category: "arrows", tags: ["bold right", "سهم"] },
  { char: "⮔", category: "arrows", tags: ["bold down", "سهم"] },
  { char: "⮐", category: "arrows", tags: ["return", "سهم"] },
  { char: "⮑", category: "arrows", tags: ["return down", "سهم"] },

  // —— More math ——
  { char: "≡", category: "math", tags: ["identical", "equivalent", "متطابق"] },
  { char: "≢", category: "math", tags: ["not identical"] },
  { char: "≪", category: "math", tags: ["much less"] },
  { char: "≫", category: "math", tags: ["much greater"] },
  { char: "⊕", category: "math", tags: ["oplus", "xor"] },
  { char: "⊗", category: "math", tags: ["otimes", "tensor"] },
  { char: "⊂", category: "math", tags: ["subset"] },
  { char: "⊃", category: "math", tags: ["superset"] },
  { char: "∈", category: "math", tags: ["element", "member", "ينتمي"] },
  { char: "∉", category: "math", tags: ["not element"] },
  { char: "∅", category: "math", tags: ["empty set", "فارغ"] },
  { char: "∩", category: "math", tags: ["intersection"] },
  { char: "∪", category: "math", tags: ["union"] },
  { char: "∠", category: "math", tags: ["angle", "زاوية"] },
  { char: "⊥", category: "math", tags: ["perpendicular"] },
  { char: "∥", category: "math", tags: ["parallel"] },
  { char: "≃", category: "math", tags: ["asymptotic"] },
  { char: "∝", category: "math", tags: ["proportional"] },
  { char: "∀", category: "math", tags: ["for all", "logic"] },
  { char: "∃", category: "math", tags: ["exists", "logic"] },
  { char: "¬", category: "math", tags: ["not", "logic"] },
  { char: "∧", category: "math", tags: ["and", "logic"] },
  { char: "∨", category: "math", tags: ["or", "logic"] },
  { char: "⊢", category: "math", tags: ["proves", "logic"] },
  { char: "⅓", category: "math", tags: ["third", "fraction", "كسر"] },
  { char: "⅔", category: "math", tags: ["two thirds", "كسر"] },
  { char: "⅕", category: "math", tags: ["fifth", "كسر"] },
  { char: "⅖", category: "math", tags: ["fraction"] },
  { char: "⅗", category: "math", tags: ["fraction"] },
  { char: "⅘", category: "math", tags: ["fraction"] },
  { char: "⅙", category: "math", tags: ["sixth"] },
  { char: "⅛", category: "math", tags: ["eighth"] },
  { char: "⅜", category: "math", tags: ["fraction"] },
  { char: "⅝", category: "math", tags: ["fraction"] },
  { char: "⅞", category: "math", tags: ["fraction"] },

  // —— Shapes ——
  { char: "■", category: "shapes", tags: ["square", "filled", "مربع"] },
  { char: "□", category: "shapes", tags: ["square", "outline", "مربع"] },
  { char: "▲", category: "shapes", tags: ["triangle", "up", "مثلث"] },
  { char: "△", category: "shapes", tags: ["triangle", "outline"] },
  { char: "▼", category: "shapes", tags: ["triangle", "down"] },
  { char: "▽", category: "shapes", tags: ["triangle", "outline down"] },
  { char: "▶", category: "shapes", tags: ["play", "right", "مثلث"] },
  { char: "◀", category: "shapes", tags: ["left", "triangle"] },
  { char: "▬", category: "shapes", tags: ["rectangle", "bar", "شريط"] },
  { char: "▭", category: "shapes", tags: ["rectangle", "outline"] },
  { char: "▮", category: "shapes", tags: ["bar", "vertical"] },
  { char: "▯", category: "shapes", tags: ["bar", "outline"] },
  { char: "▰", category: "shapes", tags: ["parallelogram"] },
  { char: "▱", category: "shapes", tags: ["parallelogram", "outline"] },
  { char: "◧", category: "shapes", tags: ["square", "left fill"] },
  { char: "◨", category: "shapes", tags: ["square", "right fill"] },
  { char: "◩", category: "shapes", tags: ["square", "top fill"] },
  { char: "◪", category: "shapes", tags: ["square", "bottom fill"] },
  { char: "⬛", category: "shapes", tags: ["black square", "مربع"] },
  { char: "⬜", category: "shapes", tags: ["white square"] },
  { char: "🔲", category: "shapes", tags: ["button square"] },
  { char: "🔳", category: "shapes", tags: ["button outline"] },
  { char: "⬟", category: "shapes", tags: ["pentagon"] },
  { char: "⬠", category: "shapes", tags: ["hexagon"] },
  { char: "⬡", category: "shapes", tags: ["hexagon", "outline"] },
  { char: "⬢", category: "shapes", tags: ["hexagon", "black"] },
  { char: "◐", category: "shapes", tags: ["circle", "half"] },
  { char: "◑", category: "shapes", tags: ["circle", "half"] },
  { char: "◒", category: "shapes", tags: ["circle", "half"] },
  { char: "◓", category: "shapes", tags: ["circle", "half"] },

  // —— Numbers ——
  { char: "①", category: "numbers", tags: ["one", "circled", "رقم"] },
  { char: "②", category: "numbers", tags: ["two", "circled", "رقم"] },
  { char: "③", category: "numbers", tags: ["three", "circled", "رقم"] },
  { char: "④", category: "numbers", tags: ["four", "circled"] },
  { char: "⑤", category: "numbers", tags: ["five", "circled"] },
  { char: "⑥", category: "numbers", tags: ["six", "circled"] },
  { char: "⑦", category: "numbers", tags: ["seven", "circled"] },
  { char: "⑧", category: "numbers", tags: ["eight", "circled"] },
  { char: "⑨", category: "numbers", tags: ["nine", "circled"] },
  { char: "⑩", category: "numbers", tags: ["ten", "circled"] },
  { char: "Ⅰ", category: "numbers", tags: ["roman", "one", "روماني"] },
  { char: "Ⅱ", category: "numbers", tags: ["roman", "two"] },
  { char: "Ⅲ", category: "numbers", tags: ["roman", "three"] },
  { char: "Ⅳ", category: "numbers", tags: ["roman", "four"] },
  { char: "Ⅴ", category: "numbers", tags: ["roman", "five"] },
  { char: "Ⅵ", category: "numbers", tags: ["roman", "six"] },
  { char: "Ⅶ", category: "numbers", tags: ["roman", "seven"] },
  { char: "Ⅷ", category: "numbers", tags: ["roman", "eight"] },
  { char: "Ⅸ", category: "numbers", tags: ["roman", "nine"] },
  { char: "Ⅹ", category: "numbers", tags: ["roman", "ten"] },
  { char: "⁰", category: "numbers", tags: ["superscript", "zero"] },
  { char: "¹", category: "numbers", tags: ["superscript", "one"] },
  { char: "²", category: "numbers", tags: ["superscript", "two", "تربيع"] },
  { char: "³", category: "numbers", tags: ["superscript", "three"] },
  { char: "⁴", category: "numbers", tags: ["superscript", "four"] },
  { char: "₀", category: "numbers", tags: ["subscript", "zero"] },
  { char: "₁", category: "numbers", tags: ["subscript", "one"] },
  { char: "₂", category: "numbers", tags: ["subscript", "two"] },
  { char: "₃", category: "numbers", tags: ["subscript", "three"] },

  // —— More symbols ——
  { char: "✉", category: "symbols", tags: ["email", "envelope", "بريد"] },
  { char: "✎", category: "symbols", tags: ["pencil", "edit", "قلم"] },
  { char: "✏", category: "symbols", tags: ["pencil"] },
  { char: "✂", category: "symbols", tags: ["scissors", "مقص"] },
  { char: "✈", category: "symbols", tags: ["plane", "travel", "طائرة"] },
  { char: "☼", category: "symbols", tags: ["sun", "bright", "شمس"] },
  { char: "☾", category: "symbols", tags: ["moon", "crescent", "قمر"] },
  { char: "☽", category: "symbols", tags: ["moon", "قمر"] },
  { char: "☃", category: "symbols", tags: ["snowman", "ثلج"] },
  { char: "☄", category: "symbols", tags: ["comet"] },
  { char: "☘", category: "symbols", tags: ["shamrock", "clover"] },
  { char: "☕", category: "symbols", tags: ["coffee", "قهوة"] },
  { char: "☠", category: "symbols", tags: ["skull", "pirate"] },
  { char: "☹", category: "symbols", tags: ["sad", "frown"] },
  { char: "☺", category: "symbols", tags: ["smile", "happy", "ابتسامة"] },
  { char: "♫", category: "symbols", tags: ["music", "note", "موسيقى"] },
  { char: "♪", category: "symbols", tags: ["music", "note"] },
  { char: "♬", category: "symbols", tags: ["music", "notes"] },
  { char: "♛", category: "symbols", tags: ["crown", "queen", "تاج"] },
  { char: "♚", category: "symbols", tags: ["crown", "king"] },
  { char: "♜", category: "symbols", tags: ["chess", "rook"] },
  { char: "♞", category: "symbols", tags: ["chess", "knight"] },
  { char: "⌛", category: "symbols", tags: ["hourglass", "time", "وقت"] },
  { char: "⏳", category: "symbols", tags: ["hourglass", "time"] },
  { char: "⌚", category: "symbols", tags: ["watch", "time"] },
  { char: "⏰", category: "symbols", tags: ["alarm", "clock"] },
  { char: "⌂", category: "symbols", tags: ["home", "house", "منزل"] },
  { char: "✿", category: "symbols", tags: ["flower", "زهرة"] },
  { char: "❀", category: "symbols", tags: ["flower"] },
  { char: "❁", category: "symbols", tags: ["flower"] },

  // —— More punctuation ——
  { char: "\u201C", category: "punctuation", tags: ["quote", "left", "علامة تنصيص"] },
  { char: "\u201D", category: "punctuation", tags: ["quote", "right"] },
  { char: "\u2018", category: "punctuation", tags: ["apostrophe", "single"] },
  { char: "\u2019", category: "punctuation", tags: ["apostrophe", "right"] },
  { char: "‧", category: "punctuation", tags: ["hyphenation point"] },
  { char: "‥", category: "punctuation", tags: ["two dot leader"] },
  { char: "⁂", category: "punctuation", tags: ["asterism"] },
  { char: "⁎", category: "punctuation", tags: ["asterisk", "نجمة"] },
  { char: "‖", category: "punctuation", tags: ["double vertical"] },
  { char: "‗", category: "punctuation", tags: ["double low line"] },

  // —— More latin ——
  { char: "á", category: "latin", tags: ["a acute", "accent"] },
  { char: "í", category: "latin", tags: ["i acute"] },
  { char: "ó", category: "latin", tags: ["o acute"] },
  { char: "ú", category: "latin", tags: ["u acute"] },
  { char: "ý", category: "latin", tags: ["y acute"] },
  { char: "ã", category: "latin", tags: ["a tilde"] },
  { char: "õ", category: "latin", tags: ["o tilde"] },
  { char: "ë", category: "latin", tags: ["e diaeresis"] },
  { char: "ï", category: "latin", tags: ["i diaeresis"] },
  { char: "ÿ", category: "latin", tags: ["y diaeresis"] },
  { char: "č", category: "latin", tags: ["c caron"] },
  { char: "š", category: "latin", tags: ["s caron"] },
  { char: "ž", category: "latin", tags: ["z caron"] },
  { char: "ł", category: "latin", tags: ["l stroke", "polish"] },
  { char: "đ", category: "latin", tags: ["d stroke"] },
  { char: "ħ", category: "latin", tags: ["h bar"] },
  { char: "ı", category: "latin", tags: ["dotless i", "turkish"] },
  { char: "ĳ", category: "latin", tags: ["ij ligature", "dutch"] },

  // —— More arabic ——
  { char: "ﷲ", category: "arabic", tags: ["allah", "الله"] },
  { char: "ﷺ", category: "arabic", tags: ["salawat", "صلى"] },
  { char: "ٱ", category: "arabic", tags: ["alef wasla"] },
  { char: "ٰ", category: "arabic", tags: ["superscript alef"] },
  { char: "ٔ", category: "arabic", tags: ["hamza above"] },
  { char: "ٕ", category: "arabic", tags: ["hamza below"] },
  { char: "ـ", category: "arabic", tags: ["tatweel", "kashida", "مد"] },

  // —— Emoji (common) ——
  { char: "😀", category: "emoji", tags: ["smile", "happy", "وجه", "ابتسامة"] },
  { char: "😃", category: "emoji", tags: ["smile", "happy"] },
  { char: "😄", category: "emoji", tags: ["smile", "laugh"] },
  { char: "😁", category: "emoji", tags: ["grin"] },
  { char: "😅", category: "emoji", tags: ["sweat", "smile"] },
  { char: "😂", category: "emoji", tags: ["joy", "laugh", "ضحك"] },
  { char: "🤣", category: "emoji", tags: ["rofl", "laugh"] },
  { char: "😊", category: "emoji", tags: ["blush", "smile"] },
  { char: "😍", category: "emoji", tags: ["love", "eyes", "حب"] },
  { char: "🥰", category: "emoji", tags: ["love", "hearts"] },
  { char: "😘", category: "emoji", tags: ["kiss"] },
  { char: "😎", category: "emoji", tags: ["cool", "sunglasses"] },
  { char: "🤔", category: "emoji", tags: ["think", "thinking", "تفكير"] },
  { char: "😢", category: "emoji", tags: ["cry", "sad", "حزن"] },
  { char: "😭", category: "emoji", tags: ["sob", "cry"] },
  { char: "😡", category: "emoji", tags: ["angry", "غضب"] },
  { char: "👍", category: "emoji", tags: ["thumbs up", "like", "موافق"] },
  { char: "👎", category: "emoji", tags: ["thumbs down", "dislike"] },
  { char: "👏", category: "emoji", tags: ["clap", "applause", "تصفيق"] },
  { char: "🙏", category: "emoji", tags: ["pray", "thanks", "شكر"] },
  { char: "💪", category: "emoji", tags: ["muscle", "strong", "قوة"] },
  { char: "❤️", category: "emoji", tags: ["heart", "love", "قلب", "حب"] },
  { char: "🧡", category: "emoji", tags: ["heart", "orange"] },
  { char: "💛", category: "emoji", tags: ["heart", "yellow"] },
  { char: "💚", category: "emoji", tags: ["heart", "green"] },
  { char: "💙", category: "emoji", tags: ["heart", "blue"] },
  { char: "💜", category: "emoji", tags: ["heart", "purple"] },
  { char: "🖤", category: "emoji", tags: ["heart", "black"] },
  { char: "💔", category: "emoji", tags: ["broken heart"] },
  { char: "⭐", category: "emoji", tags: ["star", "نجمة"] },
  { char: "🌟", category: "emoji", tags: ["star", "glow", "نجمة"] },
  { char: "✨", category: "emoji", tags: ["sparkles", "نجمة"] },
  { char: "🔥", category: "emoji", tags: ["fire", "hot", "نار"] },
  { char: "✅", category: "emoji", tags: ["check", "done", "صح"] },
  { char: "❌", category: "emoji", tags: ["cross", "no", "خطأ"] },
  { char: "⚠️", category: "emoji", tags: ["warning", "تحذير"] },
  { char: "🎉", category: "emoji", tags: ["party", "celebrate", "احتفال"] },
  { char: "🎁", category: "emoji", tags: ["gift", "هدية"] },
  { char: "📌", category: "emoji", tags: ["pin", "دبوس"] },
  { char: "📎", category: "emoji", tags: ["paperclip", "مشبك"] },
  { char: "🔗", category: "emoji", tags: ["link", "رابط"] },
  { char: "📧", category: "emoji", tags: ["email", "بريد"] },
  { char: "📱", category: "emoji", tags: ["phone", "mobile", "جوال"] },
  { char: "💻", category: "emoji", tags: ["laptop", "computer", "حاسوب"] },
  { char: "🖥️", category: "emoji", tags: ["desktop", "monitor"] },
  { char: "⌨️", category: "emoji", tags: ["keyboard", "لوحة مفاتيح"] },
  { char: "🖱️", category: "emoji", tags: ["mouse"] },
  { char: "📝", category: "emoji", tags: ["memo", "note", "ملاحظة"] },
  { char: "📅", category: "emoji", tags: ["calendar", "تقويم"] },
  { char: "⏰", category: "emoji", tags: ["alarm", "clock"] },
  { char: "🔒", category: "emoji", tags: ["lock", "secure", "قفل"] },
  { char: "🔓", category: "emoji", tags: ["unlock"] },
  { char: "🔑", category: "emoji", tags: ["key", "مفتاح"] },
  { char: "🔍", category: "emoji", tags: ["search", "بحث"] },
  { char: "💡", category: "emoji", tags: ["idea", "lightbulb", "فكرة"] },
  { char: "🌍", category: "emoji", tags: ["earth", "world", "عالم"] },
  { char: "🌙", category: "emoji", tags: ["moon", "قمر"] },
  { char: "☀️", category: "emoji", tags: ["sun", "شمس"] },
  { char: "🌈", category: "emoji", tags: ["rainbow", "قوس قزح"] },
  { char: "☁️", category: "emoji", tags: ["cloud", "سحاب"] },
  { char: "🌧️", category: "emoji", tags: ["rain", "مطر"] },
  { char: "❄️", category: "emoji", tags: ["snow", "ثلج"] },

  // —— Mac / iOS keys ——
  { char: "⌘", category: "techMac", tags: ["command", "cmd", "mac", "ماك"] },
  { char: "⌥", category: "techMac", tags: ["option", "alt", "mac"] },
  { char: "⇧", category: "techMac", tags: ["shift", "mac", "keyboard"] },
  { char: "⌃", category: "techMac", tags: ["control", "ctrl", "mac"] },
  { char: "⎋", category: "techMac", tags: ["escape", "esc", "mac"] },
  { char: "⏎", category: "techMac", tags: ["return", "enter", "mac"] },
  { char: "⌫", category: "techMac", tags: ["delete", "backspace", "mac"] },
  { char: "⌦", category: "techMac", tags: ["forward delete", "mac"] },
  { char: "⇥", category: "techMac", tags: ["tab", "mac"] },
  { char: "⇪", category: "techMac", tags: ["caps lock", "mac"] },
  { char: "⌤", category: "techMac", tags: ["enter", "mac"] },
  { char: "⌧", category: "techMac", tags: ["clear", "mac"] },
  { char: "⌖", category: "techMac", tags: ["position", "mac"] },
  { char: "⌁", category: "techMac", tags: ["home", "mac"] },
  { char: "⌂", category: "techMac", tags: ["home", "mac"] },
  { char: "⌨", category: "techMac", tags: ["keyboard", "mac"] },

  // —— Windows keys ——
  { char: "⊞", category: "techWindows", tags: ["windows", "win key", "ويندوز"] },
  { char: "⌨", category: "techWindows", tags: ["keyboard", "windows"] },
  { char: "⎀", category: "techWindows", tags: ["help", "windows"] },
  { char: "⎗", category: "techWindows", tags: ["undo", "windows"] },
  { char: "⎘", category: "techWindows", tags: ["redo", "windows"] },
  { char: "␣", category: "techWindows", tags: ["space", "bar", "مسافة"] },
  { char: "↵", category: "techWindows", tags: ["enter", "return", "ويندوز"] },
  { char: "⌦", category: "techWindows", tags: ["delete", "windows"] },
  { char: "⌫", category: "techWindows", tags: ["backspace", "windows"] },
  { char: "Ctrl", category: "techWindows", tags: ["control", "ctrl", "ويندوز", "control key"] },
  { char: "Alt", category: "techWindows", tags: ["alt", "alternate", "ويندوز"] },
  { char: "Shift", category: "techWindows", tags: ["shift", "ويندوز"] },
  { char: "Esc", category: "techWindows", tags: ["escape", "esc", "ويندوز"] },
  { char: "Del", category: "techWindows", tags: ["delete", "ويندوز"] },
  { char: "Ins", category: "techWindows", tags: ["insert", "ويندوز"] },
  { char: "PgUp", category: "techWindows", tags: ["page up", "ويندوز"] },
  { char: "PgDn", category: "techWindows", tags: ["page down", "ويندوز"] },

  // —— Android / mobile ——
  { char: "☰", category: "techAndroid", tags: ["menu", "hamburger", "android", "قائمة"] },
  { char: "⋮", category: "techAndroid", tags: ["more", "vertical", "android", "خيارات"] },
  { char: "⋯", category: "techAndroid", tags: ["more", "horizontal", "android"] },
  { char: "⌂", category: "techAndroid", tags: ["home", "android"] },
  { char: "◁", category: "techAndroid", tags: ["back", "android", "رجوع"] },
  { char: "▷", category: "techAndroid", tags: ["play", "android"] },
  { char: "⏸", category: "techAndroid", tags: ["pause", "android", "إيقاف"] },
  { char: "⏹", category: "techAndroid", tags: ["stop", "android"] },
  { char: "⏺", category: "techAndroid", tags: ["record", "android"] },
  { char: "⏭", category: "techAndroid", tags: ["next", "skip", "android"] },
  { char: "⏮", category: "techAndroid", tags: ["previous", "android"] },
  { char: "🔋", category: "techAndroid", tags: ["battery", "android", "بطارية"] },
  { char: "📶", category: "techAndroid", tags: ["signal", "wifi", "شبكة"] },
  { char: "🔔", category: "techAndroid", tags: ["notification", "bell", "إشعار"] },
  { char: "🔕", category: "techAndroid", tags: ["mute", "silent"] },
  { char: "📳", category: "techAndroid", tags: ["vibrate", "اهتزاز"] },
];
