// Generated by scripts/generate-assets.ts — do not edit manually.
import type { CategoryId } from "./categories";

export interface ToolLite {
  slug: string;
  category: CategoryId;
  icon: string;
  title: string;
  description: string;
  keywords: string[];
  titleAr: string;
  descriptionAr: string;
  keywordsAr: string[];
  isNew?: boolean;
}

export const toolsLite: ToolLite[] = [
  {
    "slug": "merge-pdf",
    "category": "pdf",
    "icon": "Files",
    "title": "Merge PDF",
    "description": "Combine multiple PDF files into one document. Drag to reorder pages.",
    "keywords": [
      "merge pdf",
      "combine pdf",
      "join pdf",
      "pdf merger",
      "pdf combiner"
    ],
    "titleAr": "دمج PDF",
    "descriptionAr": "اجمع عدة ملفات PDF في مستند واحد. اسحب لإعادة ترتيب الصفحات.",
    "keywordsAr": [
      "دمج pdf",
      "جمع pdf",
      "ربط pdf",
      "أداة دمج pdf",
      "دمج ملفات pdf"
    ]
  },
  {
    "slug": "split-pdf",
    "category": "pdf",
    "icon": "Scissors",
    "title": "Split PDF",
    "description": "Split a PDF into separate files by page ranges or individual pages.",
    "keywords": [
      "split pdf",
      "extract pdf pages",
      "pdf splitter",
      "separate pdf pages"
    ],
    "titleAr": "تقسيم PDF",
    "descriptionAr": "قسّم ملف PDF إلى ملفات منفصلة حسب نطاقات الصفحات أو صفحات فردية.",
    "keywordsAr": [
      "تقسيم pdf",
      "استخراج صفحات pdf",
      "أداة تقسيم pdf",
      "فصل صفحات pdf"
    ]
  },
  {
    "slug": "pdf-to-jpg",
    "category": "pdf",
    "icon": "ArrowLeftRight",
    "title": "PDF to JPG & JPG to PDF Converter",
    "description": "Convert PDF pages to JPG images, or combine JPG/PNG/WebP images into a single PDF.",
    "keywords": [
      "pdf to jpg",
      "pdf to image",
      "convert pdf to jpeg",
      "pdf page to image",
      "jpg to pdf",
      "image to pdf",
      "png to pdf",
      "photos to pdf",
      "combine images pdf"
    ],
    "titleAr": "تحويل PDF إلى JPG والعكس",
    "descriptionAr": "حوّل صفحات PDF إلى صور JPG، أو اجمع صور JPG وPNG وWebP في ملف PDF واحد.",
    "keywordsAr": [
      "pdf إلى jpg",
      "pdf إلى صورة",
      "تحويل pdf إلى jpeg",
      "صفحة pdf إلى صورة",
      "jpg إلى pdf",
      "صورة إلى pdf",
      "png إلى pdf",
      "دمج صور pdf",
      "تحويل صور pdf"
    ]
  },
  {
    "slug": "compress-pdf",
    "category": "pdf",
    "icon": "Minimize2",
    "title": "Compress PDF",
    "description": "Reduce PDF file size with lossless optimization or strong raster compression.",
    "keywords": [
      "compress pdf",
      "reduce pdf size",
      "shrink pdf",
      "pdf compressor",
      "optimize pdf"
    ],
    "titleAr": "ضغط PDF",
    "descriptionAr": "قلّل حجم ملف PDF بتحسين البنية أو ضغط قوي يحوّل الصفحات إلى صور.",
    "keywordsAr": [
      "ضغط pdf",
      "تصغير pdf",
      "تقليل حجم pdf",
      "أداة ضغط pdf",
      "تحسين pdf"
    ]
  },
  {
    "slug": "rotate-pdf",
    "category": "pdf",
    "icon": "RotateCw",
    "title": "Rotate PDF",
    "description": "Rotate PDF pages 90° at a time. Preview thumbnails and rotate all pages at once.",
    "keywords": [
      "rotate pdf",
      "turn pdf pages",
      "pdf rotation",
      "rotate pdf online",
      "flip pdf pages"
    ],
    "titleAr": "تدوير PDF",
    "descriptionAr": "دوّر صفحات PDF بمقدار 90°. معاينة الصور المصغرة وتدوير كل الصفحات دفعة واحدة.",
    "keywordsAr": [
      "تدوير pdf",
      "قلب صفحات pdf",
      "تدوير صفحات pdf",
      "أداة تدوير pdf"
    ]
  },
  {
    "slug": "organize-pdf",
    "category": "pdf",
    "icon": "LayoutGrid",
    "title": "Organize PDF",
    "description": "Reorder and delete PDF pages with drag-and-drop thumbnails. Export a new document.",
    "keywords": [
      "organize pdf",
      "reorder pdf pages",
      "delete pdf pages",
      "arrange pdf",
      "pdf page editor"
    ],
    "titleAr": "تنظيم PDF",
    "descriptionAr": "أعد ترتيب صفحات PDF واحذفها بالسحب والإفلات. صدّر مستنداً جديداً.",
    "keywordsAr": [
      "تنظيم pdf",
      "إعادة ترتيب صفحات pdf",
      "حذف صفحات pdf",
      "ترتيب pdf"
    ]
  },
  {
    "slug": "extract-pages",
    "category": "pdf",
    "icon": "FileOutput",
    "title": "Extract PDF Pages",
    "description": "Pull selected pages out of a PDF into a new file or separate PDFs. Click thumbnails or type page ranges.",
    "keywords": [
      "extract pdf pages",
      "pull pages from pdf",
      "copy pdf pages",
      "save pdf pages",
      "extract pages from pdf"
    ],
    "titleAr": "استخراج صفحات PDF",
    "descriptionAr": "اسحب الصفحات المحددة من PDF إلى ملف جديد أو ملفات PDF منفصلة. انقر على الصور المصغرة أو اكتب نطاق الصفحات.",
    "keywordsAr": [
      "استخراج صفحات pdf",
      "سحب صفحات من pdf",
      "نسخ صفحات pdf",
      "حفظ صفحات pdf"
    ]
  },
  {
    "slug": "pdf-sign",
    "category": "pdf",
    "icon": "PenLine",
    "title": "Sign PDF Online",
    "description": "Draw your signature and stamp it on a PDF document. No account or upload to servers.",
    "keywords": [
      "sign pdf online",
      "pdf signature",
      "electronic signature pdf",
      "e-sign pdf"
    ],
    "titleAr": "توقيع PDF إلكترونياً",
    "descriptionAr": "ارسم توقيعك وختمه على مستند PDF دون رفع الملف إلى خوادمنا.",
    "keywordsAr": [
      "توقيع pdf الكترونيا",
      "توقيع pdf",
      "توقيع إلكتروني pdf",
      "ختم pdf"
    ]
  },
  {
    "slug": "pdf-watermark",
    "category": "pdf",
    "icon": "Droplets",
    "title": "Add Watermark to PDF",
    "description": "Add a text watermark to every page of your PDF. Adjust opacity before downloading.",
    "keywords": [
      "add watermark to pdf",
      "pdf watermark",
      "stamp pdf",
      "watermark pdf online"
    ],
    "titleAr": "علامة مائية على PDF",
    "descriptionAr": "أضف علامة مائية نصية على كل صفحات PDF مع التحكم في الشفافية.",
    "keywordsAr": [
      "علامة مائية على pdf",
      "علامة مائية pdf",
      "ختم نصي pdf"
    ]
  },
  {
    "slug": "pdf-protect",
    "category": "pdf",
    "icon": "Lock",
    "title": "Password Protect PDF",
    "description": "Encrypt a PDF with a password. Lock your document before sharing.",
    "keywords": [
      "password protect pdf",
      "encrypt pdf",
      "lock pdf",
      "pdf password online"
    ],
    "titleAr": "حماية PDF بكلمة سر",
    "descriptionAr": "شفّر ملف PDF بكلمة مرور قبل مشاركته.",
    "keywordsAr": [
      "حماية pdf بكلمة سر",
      "تشفير pdf",
      "قفل pdf",
      "كلمة مرور pdf"
    ]
  },
  {
    "slug": "compress-image",
    "category": "image",
    "icon": "Minimize2",
    "title": "Compress Image",
    "description": "Reduce JPG and PNG file size with adjustable quality. No upload required.",
    "keywords": [
      "compress image",
      "reduce image size",
      "jpg compressor",
      "png compressor",
      "optimize image"
    ],
    "titleAr": "ضغط الصور",
    "descriptionAr": "قلّل حجم ملفات JPG وPNG بجودة قابلة للتعديل. لا حاجة لرفع الملفات.",
    "keywordsAr": [
      "ضغط الصور",
      "تقليل حجم الصورة",
      "ضاغط jpg",
      "ضاغط png",
      "تحسين الصور"
    ]
  },
  {
    "slug": "image-resizer",
    "category": "image",
    "icon": "Scaling",
    "title": "Image Resizer",
    "description": "Resize images to exact pixel dimensions with optional aspect ratio lock.",
    "keywords": [
      "resize image",
      "image resizer",
      "scale image",
      "change image dimensions"
    ],
    "titleAr": "تغيير حجم الصور",
    "descriptionAr": "غيّر أبعاد الصور إلى أبعاد بكسل محددة مع خيار قفل نسبة العرض إلى الارتفاع.",
    "keywordsAr": [
      "تغيير حجم الصورة",
      "مغيّر حجم الصور",
      "تكبير وتصغير الصور",
      "تعديل أبعاد الصورة"
    ]
  },
  {
    "slug": "crop-image",
    "category": "image",
    "icon": "Crop",
    "title": "Crop Image",
    "description": "Crop images with a rectangle, circle, or rounded frame — right in your browser.",
    "keywords": [
      "crop image",
      "image cropper",
      "trim image",
      "cut image",
      "circle crop",
      "round profile picture",
      "circular crop",
      "rounded square crop"
    ],
    "titleAr": "قص الصور",
    "descriptionAr": "قص الصور بإطار مستطيل أو دائري أو مستدير الزوايا — كل شيء في متصفحك.",
    "keywordsAr": [
      "قص الصور",
      "أداة قص الصور",
      "تقليم الصور",
      "قطع الصور",
      "قص دائري",
      "صورة شخصية دائرية",
      "قص مربع مستدير"
    ]
  },
  {
    "slug": "image-converter",
    "category": "image",
    "icon": "ArrowLeftRight",
    "title": "Image Converter",
    "description": "Convert images between PNG, JPG, and WebP formats in your browser.",
    "keywords": [
      "image converter",
      "png to jpg",
      "jpg to png",
      "webp converter",
      "convert image format"
    ],
    "titleAr": "محوّل الصور",
    "descriptionAr": "حوّل الصور بين صيغ PNG وJPG وWebP في متصفحك.",
    "keywordsAr": [
      "محوّل الصور",
      "png إلى jpg",
      "jpg إلى png",
      "محوّل webp",
      "تحويل صيغة الصورة"
    ]
  },
  {
    "slug": "heic-to-jpg",
    "category": "image",
    "icon": "ImageDown",
    "title": "HEIC to JPG Converter",
    "description": "Convert iPhone HEIC photos to JPG locally. Batch convert and download as ZIP.",
    "keywords": [
      "heic to jpg",
      "convert heic",
      "iphone photo to jpg",
      "heic converter"
    ],
    "titleAr": "تحويل HEIC إلى JPG",
    "descriptionAr": "حوّل صور iPhone بصيغة HEIC إلى JPG محلياً. تحويل دفعي وتنزيل ZIP.",
    "keywordsAr": [
      "heic الى jpg",
      "تحويل heic",
      "صورة ايفون jpg",
      "محول heic"
    ],
    "isNew": true
  },
  {
    "slug": "flip-image",
    "category": "image",
    "icon": "FlipHorizontal2",
    "title": "Flip Image",
    "description": "Flip images horizontally, vertically, or both. Instant preview, keeps PNG or JPG format.",
    "keywords": [
      "flip image",
      "mirror image",
      "flip photo horizontal",
      "flip vertical"
    ],
    "titleAr": "قلب صورة",
    "descriptionAr": "اقلب الصورة أفقياً أو عمودياً أو بالاتجاهين. معاينة فورية مع الحفاظ على PNG أو JPG.",
    "keywordsAr": [
      "قلب صورة",
      "عكس صورة",
      "mirror image",
      "flip photo"
    ],
    "isNew": true
  },
  {
    "slug": "image-rotator",
    "category": "image",
    "icon": "RotateCw",
    "title": "Image Rotator",
    "description": "Rotate images 90°, 180°, or 270° in your browser. Download as PNG.",
    "keywords": [
      "rotate image",
      "image rotator",
      "turn image",
      "rotate photo"
    ],
    "titleAr": "تدوير الصور",
    "descriptionAr": "دوّر الصور 90° أو 180° أو 270° في متصفحك. نزّل PNG.",
    "keywordsAr": [
      "تدوير صورة",
      "أداة تدوير الصور",
      "rotate image",
      "image rotator",
      "تدوير الصور"
    ],
    "isNew": true
  },
  {
    "slug": "blur-image",
    "category": "image",
    "icon": "ScanFace",
    "title": "Blur & Pixelate Image",
    "description": "Draw rectangles to blur or pixelate sensitive areas before sharing. 100% local processing.",
    "keywords": [
      "blur part of image",
      "pixelate image",
      "pixelate region",
      "censor image",
      "hide face in photo",
      "privacy blur",
      "blur face"
    ],
    "titleAr": "تمويه وبكسلة الصور",
    "descriptionAr": "ارسم مستطيلات لتمويه أو تبكسل المناطق الحساسة قبل المشاركة. معالجة محلية 100%.",
    "keywordsAr": [
      "تمويه جزء من صورة",
      "بكسلة صور",
      "اخفاء وجه",
      "censor image",
      "pixelate image",
      "خصوصية صورة",
      "تمويه وجه"
    ],
    "isNew": true
  },
  {
    "slug": "image-watermark",
    "category": "image",
    "icon": "Droplets",
    "title": "Image Watermark",
    "description": "Add draggable text watermarks with opacity, rotation, and tile mode. Export in original format.",
    "keywords": [
      "image watermark",
      "add watermark to photo",
      "text watermark",
      "watermark maker"
    ],
    "titleAr": "علامة مائية على صورة",
    "descriptionAr": "أضف علامة مائية نصية قابلة للسحب مع الشفافية والتدوير ووضع التكرار. صدّر بنفس الصيغة.",
    "keywordsAr": [
      "علامة مائية",
      "watermark صورة",
      "نص على صورة",
      "حماية صورة"
    ],
    "isNew": true
  },
  {
    "slug": "add-text-to-image",
    "category": "image",
    "icon": "PenLine",
    "title": "Add Text to Image",
    "description": "Overlay custom text on any image with size, color, and position controls. Export PNG.",
    "keywords": [
      "add text to image",
      "text overlay",
      "caption image",
      "write on photo"
    ],
    "titleAr": "إضافة نص على الصورة",
    "descriptionAr": "ضع نصاً مخصصاً على أي صورة مع التحكم بالحجم واللون والموضع. صدّر PNG.",
    "keywordsAr": [
      "اضافة نص على صورة",
      "caption صورة",
      "كتابة على صورة",
      "text overlay",
      "تعليق على صورة"
    ],
    "isNew": true
  },
  {
    "slug": "image-collage",
    "category": "image",
    "icon": "LayoutGrid",
    "title": "Image Collage Maker",
    "description": "Combine 2–4 photos into a grid collage with adjustable gap. Download as one PNG.",
    "keywords": [
      "image collage",
      "photo grid",
      "combine photos",
      "collage maker online"
    ],
    "titleAr": "صانع كولاج الصور",
    "descriptionAr": "ادمج 2–4 صور في شبكة كولاج مع فجوة قابلة للضبط. نزّل PNG واحداً.",
    "keywordsAr": [
      "كولاج صور",
      "دمج صور",
      "photo grid",
      "collage maker",
      "شبكة صور"
    ],
    "isNew": true
  },
  {
    "slug": "passport-photo",
    "category": "image",
    "icon": "IdCard",
    "title": "Passport Photo Maker",
    "description": "Crop to official passport sizes at 300 DPI. Export single photo or printable sheet.",
    "keywords": [
      "passport photo maker",
      "id photo size",
      "2x2 photo",
      "35x45mm photo"
    ],
    "titleAr": "صور شخصية بمقاسات رسمية",
    "descriptionAr": "اقصِ لأحجام جواز السفر الرسمية بدقة 300 DPI. صورة واحدة أو ورقة طباعة 4×6.",
    "keywordsAr": [
      "صورة جواز سفر",
      "صورة شخصية 35x45",
      "2x2 photo",
      "صورة هوية"
    ],
    "isNew": true
  },
  {
    "slug": "gif-maker",
    "category": "image",
    "icon": "Film",
    "title": "GIF Maker from Images",
    "description": "Combine up to 50 images into an animated GIF with frame delay and loop control.",
    "keywords": [
      "gif maker",
      "images to gif",
      "animated gif creator",
      "slideshow gif"
    ],
    "titleAr": "صانع GIF من صور",
    "descriptionAr": "اجمع حتى 50 صورة في GIF متحرك مع تأخير الإطارات والتحكم بالتكرار.",
    "keywordsAr": [
      "صانع gif",
      "صور الى gif",
      "animated gif",
      "slideshow gif"
    ],
    "isNew": true
  },
  {
    "slug": "image-color-picker",
    "category": "image",
    "icon": "Pipette",
    "title": "Image Color Picker",
    "description": "Click any pixel to get HEX, RGB, and HSL values. Copy colors with session history.",
    "keywords": [
      "image color picker",
      "pick color from image",
      "eyedropper online",
      "hex from photo"
    ],
    "titleAr": "التقاط لون من صورة",
    "descriptionAr": "انقر أي بكسل للحصول على HEX و RGB و HSL. انسخ الألوان مع سجل الجلسة.",
    "keywordsAr": [
      "منتقي لون من صورة",
      "eyedropper",
      "hex من صورة",
      "التقاط لون"
    ],
    "isNew": true
  },
  {
    "slug": "exif-remover",
    "category": "image",
    "icon": "Eraser",
    "title": "Remove EXIF Data",
    "description": "Strip GPS, camera, and metadata from photos by re-exporting through canvas.",
    "keywords": [
      "remove exif data",
      "strip metadata",
      "remove photo metadata",
      "exif remover"
    ],
    "titleAr": "إزالة بيانات EXIF",
    "descriptionAr": "أزل بيانات GPS والكاميرا والميتاداتا من الصور بإعادة رسمها على canvas.",
    "keywordsAr": [
      "إزالة بيانات exif",
      "حذف ميتاداتا الصور",
      "إزالة موقع الصورة"
    ]
  },
  {
    "slug": "word-counter",
    "category": "text",
    "icon": "Hash",
    "title": "Word Counter",
    "description": "Count words, characters, sentences, paragraphs, and estimated reading time.",
    "keywords": [
      "word counter",
      "character count",
      "text counter",
      "reading time"
    ],
    "titleAr": "عداد الكلمات",
    "descriptionAr": "احسب الكلمات والأحرف والجمل والفقرات ووقت القراءة التقديري.",
    "keywordsAr": [
      "عداد الكلمات",
      "عد الأحرف",
      "عداد النصوص",
      "وقت القراءة"
    ]
  },
  {
    "slug": "case-converter",
    "category": "text",
    "icon": "CaseSensitive",
    "title": "Case Converter",
    "description": "Convert text to uppercase, lowercase, title case, camelCase, and more.",
    "keywords": [
      "case converter",
      "uppercase",
      "lowercase",
      "title case",
      "camelcase",
      "snake case"
    ],
    "titleAr": "محوّل حالة الأحرف",
    "descriptionAr": "حوّل النص إلى أحرف كبيرة أو صغيرة أو عنوان أو camelCase والمزيد.",
    "keywordsAr": [
      "محوّل حالة الأحرف",
      "أحرف كبيرة",
      "أحرف صغيرة",
      "حالة العنوان",
      "camelcase",
      "snake case"
    ]
  },
  {
    "slug": "password-generator",
    "category": "text",
    "icon": "KeyRound",
    "title": "Password Generator",
    "description": "Create strong random passwords with customizable length and character sets.",
    "keywords": [
      "password generator",
      "random password",
      "secure password",
      "strong password"
    ],
    "titleAr": "مولّد كلمات المرور",
    "descriptionAr": "أنشئ كلمات مرور عشوائية قوية بطول ومجموعات أحرف قابلة للتخصيص.",
    "keywordsAr": [
      "مولّد كلمات المرور",
      "كلمة مرور عشوائية",
      "كلمة مرور آمنة",
      "كلمة مرور قوية"
    ]
  },
  {
    "slug": "find-and-replace",
    "category": "text",
    "icon": "Search",
    "title": "Find and Replace",
    "description": "Search and replace text with optional regex support. Replace all matches at once.",
    "keywords": [
      "find and replace",
      "text replace",
      "regex replace",
      "bulk replace"
    ],
    "titleAr": "بحث واستبدال",
    "descriptionAr": "ابحث واستبدل النص مع دعم regex اختياري. استبدل كل التطابقات دفعة واحدة.",
    "keywordsAr": [
      "بحث واستبدال",
      "find and replace",
      "استبدال نص",
      "regex replace",
      "استبدال جماعي"
    ],
    "isNew": true
  },
  {
    "slug": "remove-line-breaks",
    "category": "text",
    "icon": "WrapText",
    "title": "Remove Line Breaks",
    "description": "Remove line breaks, extra spaces, and blank lines from text instantly.",
    "keywords": [
      "remove line breaks",
      "delete line breaks",
      "clean text",
      "remove newlines",
      "remove whitespace",
      "trim lines",
      "clean spaces",
      "remove blank lines",
      "extra spaces"
    ],
    "titleAr": "إزالة فواصل الأسطر",
    "descriptionAr": "أزل فواصل الأسطر والمسافات الزائدة والأسطر الفارغة من النص فوراً.",
    "keywordsAr": [
      "إزالة فواصل الأسطر",
      "حذف فواصل الأسطر",
      "تنظيف النص",
      "إزالة الأسطر الجديدة",
      "ازالة مسافات",
      "تنظيف مسافات",
      "حذف اسطر فارغة",
      "قص اسطر",
      "مسافات زائدة"
    ]
  },
  {
    "slug": "markdown-to-html",
    "category": "text",
    "icon": "FileCode",
    "title": "Markdown to HTML",
    "description": "Convert Markdown to HTML with a live preview and copy-ready output.",
    "keywords": [
      "markdown to html",
      "md to html",
      "markdown converter",
      "markdown preview"
    ],
    "titleAr": "تحويل Markdown إلى HTML",
    "descriptionAr": "حوّل Markdown إلى HTML مع معاينة مباشرة ومخرجات جاهزة للنسخ.",
    "keywordsAr": [
      "markdown إلى html",
      "md إلى html",
      "محوّل markdown",
      "معاينة markdown"
    ]
  },
  {
    "slug": "lorem-ipsum-generator",
    "category": "text",
    "icon": "TextQuote",
    "title": "Lorem Ipsum Generator",
    "description": "Generate placeholder paragraphs, sentences, or words for mockups and drafts.",
    "keywords": [
      "lorem ipsum",
      "placeholder text",
      "dummy text",
      "lorem generator"
    ],
    "titleAr": "مولّد لوريم إيبسوم",
    "descriptionAr": "أنشئ فقرات أو جمل أو كلمات وهمية للنماذج والمسودات.",
    "keywordsAr": [
      "لوريم إيبسوم",
      "نص وهمي",
      "نص تجريبي",
      "مولّد لوريم"
    ]
  },
  {
    "slug": "text-diff-checker",
    "category": "text",
    "icon": "GitCompare",
    "title": "Text Diff Checker",
    "description": "Compare two texts side by side with highlighted additions and deletions.",
    "keywords": [
      "text diff",
      "compare text",
      "diff checker",
      "text comparison"
    ],
    "titleAr": "مقارن النصوص",
    "descriptionAr": "قارن نصين جنباً إلى جنب مع تمييز الإضافات والحذف.",
    "keywordsAr": [
      "مقارنة النصوص",
      "مقارن النصوص",
      "فروق النصوص",
      "مقارنة النص"
    ]
  },
  {
    "slug": "slug-generator",
    "category": "text",
    "icon": "Link",
    "title": "Slug Generator",
    "description": "Convert titles to clean URL slugs with lowercase letters and hyphens.",
    "keywords": [
      "slug generator",
      "url slug",
      "permalink generator",
      "seo slug"
    ],
    "titleAr": "مولّد Slug للروابط",
    "descriptionAr": "حوّل العناوين إلى slugs نظيفة للروابط بأحرف صغيرة وشرطات. مثالي لـ SEO والروابط الدائمة.",
    "keywordsAr": [
      "مولد slug",
      "رابط url",
      "permalink",
      "slug seo",
      "تحويل عنوان الى رابط"
    ],
    "isNew": true
  },
  {
    "slug": "arabic-diacritics-remover",
    "category": "text",
    "icon": "SpellCheck",
    "title": "Arabic Diacritics Remover",
    "description": "Remove Arabic tashkeel (harakat) from text instantly. Fully client-side.",
    "keywords": [
      "remove arabic diacritics",
      "remove tashkeel",
      "strip harakat",
      "arabic text cleaner"
    ],
    "titleAr": "إزالة التشكيل العربي",
    "descriptionAr": "أزل الحركات والتشكيل (tashkeel) من النص العربي فوراً. يعمل بالكامل في متصفحك دون رفع.",
    "keywordsAr": [
      "ازالة تشكيل",
      "حذف حركات",
      "ازالة تاشكيل",
      "تنظيف نص عربي",
      "strip harakat"
    ],
    "isNew": true
  },
  {
    "slug": "line-sorter",
    "category": "text",
    "icon": "ArrowLeftRight",
    "title": "Line Sorter",
    "description": "Sort lines alphabetically, reverse order, or randomly. Optionally remove duplicate lines.",
    "keywords": [
      "sort lines",
      "alphabetical sort",
      "remove duplicate lines",
      "line sorter"
    ],
    "titleAr": "ترتيب الأسطر",
    "descriptionAr": "رتّب الأسطر أبجدياً أو عكسياً أو عشوائياً. أزل الأسطر المكررة اختيارياً.",
    "keywordsAr": [
      "ترتيب اسطر",
      "فرز ابجدي",
      "حذف اسطر مكررة",
      "sort lines",
      "ترتيب قائمة"
    ],
    "isNew": true
  },
  {
    "slug": "word-frequency-counter",
    "category": "text",
    "icon": "Hash",
    "title": "Word Frequency Counter",
    "description": "Count how often each word appears in text and sort results by frequency.",
    "keywords": [
      "word frequency",
      "word count analysis",
      "text frequency counter",
      "keyword density"
    ],
    "titleAr": "عداد تكرار الكلمات",
    "descriptionAr": "احسب عدد مرات ظهور كل كلمة في النص ورتّب النتائج حسب التكرار. مفيد لتحليل SEO والكتابة.",
    "keywordsAr": [
      "تكرار الكلمات",
      "تحليل نص",
      "كثافة كلمات مفتاحية",
      "عداد تكرار",
      "word frequency"
    ],
    "isNew": true
  },
  {
    "slug": "online-notepad",
    "category": "text",
    "icon": "NotebookPen",
    "title": "Online Notepad",
    "description": "A simple notepad that auto-saves to your browser. Word and character count included.",
    "keywords": [
      "online notepad",
      "web notepad",
      "notes app",
      "auto save notepad",
      "simple notepad"
    ],
    "titleAr": "مفكرة على الإنترنت",
    "descriptionAr": "مفكرة بسيطة تحفظ تلقائياً في متصفحك. تتضمن عد الكلمات والأحرف.",
    "keywordsAr": [
      "مفكرة على الإنترنت",
      "مفكرة ويب",
      "تطبيق ملاحظات",
      "مفكرة بحفظ تلقائي",
      "مفكرة بسيطة"
    ]
  },
  {
    "slug": "text-reverser",
    "category": "text",
    "icon": "Shuffle",
    "title": "Text Reverser",
    "description": "Reverse entire text, individual lines, or word order. Useful for puzzles and testing.",
    "keywords": [
      "reverse text",
      "flip text",
      "reverse words",
      "backwards text"
    ],
    "titleAr": "عكس النص",
    "descriptionAr": "اعكس النص بالكامل أو كل سطر أو ترتيب الكلمات. مفيد للألغاز والاختبار.",
    "keywordsAr": [
      "عكس نص",
      "قلب نص",
      "reverse text",
      "عكس كلمات",
      "نص معكوس"
    ],
    "isNew": true
  },
  {
    "slug": "text-to-ascii-art",
    "category": "text",
    "icon": "Type",
    "title": "Text to ASCII Art",
    "description": "Convert text to ASCII art banners using figlet fonts. Runs in your browser.",
    "keywords": [
      "ascii art generator",
      "text to ascii",
      "figlet online",
      "ascii banner"
    ],
    "titleAr": "تحويل النص إلى ASCII Art",
    "descriptionAr": "حوّل النص إلى بanners ASCII بخطوط figlet. يعمل في متصفحك.",
    "keywordsAr": [
      "ascii art",
      "نص الى ascii",
      "figlet",
      "بانر ascii",
      "فن ascii"
    ],
    "isNew": true
  },
  {
    "slug": "character-map",
    "category": "text",
    "icon": "Keyboard",
    "title": "Character Map",
    "description": "Browse special Unicode characters and symbols. Click to copy any character instantly.",
    "keywords": [
      "character map",
      "unicode symbols",
      "special characters",
      "copy symbols"
    ],
    "titleAr": "خريطة الأحرف والرموز",
    "descriptionAr": "تصفّح رموز Unicode الخاصة والرموز. انقر لنسخ أي حرف فوراً.",
    "keywordsAr": [
      "خريطة احرف",
      "رموز unicode",
      "احرف خاصة",
      "نسخ رموز",
      "character map"
    ],
    "isNew": true
  },
  {
    "slug": "qr-code-generator",
    "category": "dev",
    "icon": "QrCode",
    "title": "QR Code Generator",
    "description": "Generate QR codes from text or URLs. Download as PNG or SVG.",
    "keywords": [
      "qr code generator",
      "qr code maker",
      "create qr code",
      "qr code download"
    ],
    "titleAr": "مولّد رمز QR",
    "descriptionAr": "أنشئ رموز QR من نص أو روابط. نزّلها بصيغة PNG أو SVG.",
    "keywordsAr": [
      "مولّد رمز qr",
      "صانع رمز qr",
      "إنشاء رمز qr",
      "تنزيل رمز qr"
    ]
  },
  {
    "slug": "barcode-generator",
    "category": "dev",
    "icon": "Barcode",
    "title": "Barcode Generator",
    "description": "Generate CODE128, EAN13, UPC, and CODE39 barcodes from text. Download as PNG.",
    "keywords": [
      "barcode generator",
      "create barcode",
      "code128 generator",
      "ean13 barcode"
    ],
    "titleAr": "مولّد الباركود",
    "descriptionAr": "ولّد باركود CODE128 أو EAN13 أو UPC أو CODE39. نزّل SVG أو PNG للملصقات والمخزون.",
    "keywordsAr": [
      "مولد باركود",
      "barcode generator",
      "ean13",
      "code128",
      "باركود اونلاين"
    ],
    "isNew": true
  },
  {
    "slug": "json-formatter",
    "category": "dev",
    "icon": "Braces",
    "title": "JSON Formatter",
    "description": "Format, validate, and minify JSON with clear error messages.",
    "keywords": [
      "json formatter",
      "json beautifier",
      "json validator",
      "json minify"
    ],
    "titleAr": "منسّق JSON",
    "descriptionAr": "نسّق وتحقق من صحة JSON وصغّره مع رسائل خطأ واضحة.",
    "keywordsAr": [
      "منسّق json",
      "تجميل json",
      "التحقق من json",
      "تصغير json"
    ]
  },
  {
    "slug": "base64",
    "category": "dev",
    "icon": "Binary",
    "title": "Base64 Encoder / Decoder",
    "description": "Encode and decode text or images to Base64. Works entirely offline.",
    "keywords": [
      "base64 encoder",
      "base64 decoder",
      "base64 converter",
      "image to base64"
    ],
    "titleAr": "مشفّر / فك تشفير Base64",
    "descriptionAr": "شفّر وفك تشفير النص أو الصور إلى Base64. يعمل بالكامل دون اتصال.",
    "keywordsAr": [
      "مشفّر base64",
      "فك تشفير base64",
      "محوّل base64",
      "صورة إلى base64"
    ]
  },
  {
    "slug": "hash-generator",
    "category": "dev",
    "icon": "Fingerprint",
    "title": "Hash Generator",
    "description": "Generate MD5, SHA-1, SHA-256, and SHA-512 hashes from any text.",
    "keywords": [
      "hash generator",
      "md5 hash",
      "sha256",
      "sha512",
      "checksum"
    ],
    "titleAr": "مولّد التجزئة",
    "descriptionAr": "أنشئ تجزئات MD5 وSHA-1 وSHA-256 وSHA-512 من أي نص.",
    "keywordsAr": [
      "مولّد التجزئة",
      "تجزئة md5",
      "sha256",
      "sha512",
      "مجموع تحقق"
    ]
  },
  {
    "slug": "uuid-generator",
    "category": "dev",
    "icon": "Hash",
    "title": "UUID Generator",
    "description": "Generate random UUID v4 identifiers. Create 1–20 UUIDs and copy them all at once.",
    "keywords": [
      "uuid generator",
      "generate uuid",
      "uuid v4",
      "random uuid"
    ],
    "titleAr": "مولّد UUID",
    "descriptionAr": "ولّد معرفات UUID v4 عشوائية. أنشئ 1–20 معرفاً وانسخها دفعة واحدة.",
    "keywordsAr": [
      "مولد uuid",
      "توليد uuid",
      "uuid v4",
      "معرف عشوائي"
    ],
    "isNew": true
  },
  {
    "slug": "color-picker",
    "category": "dev",
    "icon": "Palette",
    "title": "Color Picker",
    "description": "Pick a color and convert between HEX, RGB, and HSL formats.",
    "keywords": [
      "color picker",
      "hex to rgb",
      "rgb to hex",
      "hsl converter",
      "color converter"
    ],
    "titleAr": "منتقي الألوان",
    "descriptionAr": "اختر لوناً وحوّله بين صيغ HEX وRGB وHSL.",
    "keywordsAr": [
      "منتقي الألوان",
      "hex إلى rgb",
      "rgb إلى hex",
      "محوّل hsl",
      "محوّل الألوان"
    ]
  },
  {
    "slug": "color-code-converter",
    "category": "dev",
    "icon": "Palette",
    "title": "Color Code Converter",
    "description": "Convert between HEX, RGB, HSL, and HSV color formats from a single input value.",
    "keywords": [
      "color converter",
      "hex to rgb",
      "rgb to hsl",
      "color code converter"
    ],
    "titleAr": "محوّل أكواد الألوان",
    "descriptionAr": "حوّل بين HEX و RGB و HSL و HSV من قيمة إدخال واحدة.",
    "keywordsAr": [
      "محول الوان",
      "hex الى rgb",
      "rgb الى hsl",
      "تحويل لون"
    ],
    "isNew": true
  },
  {
    "slug": "color-palette-generator",
    "category": "dev",
    "icon": "Paintbrush",
    "title": "Color Palette Generator",
    "description": "Generate complementary, analogous, and triadic color palettes from a base color.",
    "keywords": [
      "color palette generator",
      "color scheme generator",
      "complementary colors",
      "palette maker"
    ],
    "titleAr": "مولّد لوحة ألوان",
    "descriptionAr": "ولّد تناسقات ألوان مكمّلة ومتجاورة وثلاثية من لون أساسي.",
    "keywordsAr": [
      "مولد لوحة الوان",
      "تناسق ألوان",
      "ألوان مكملة",
      "لوحة ألوان"
    ]
  },
  {
    "slug": "regex-tester",
    "category": "dev",
    "icon": "Regex",
    "title": "Regex Tester",
    "description": "Test and debug regular expressions with live highlighting. See matches and groups as you type. Runs entirely in your browser.",
    "keywords": [
      "regex tester",
      "regular expression tester",
      "regex debugger",
      "test regex online"
    ],
    "titleAr": "اختبار Regex",
    "descriptionAr": "اختبر ونقّح التعابير النمطية مع تظليل حيّ. شاهد التطابقات والمجموعات أثناء الكتابة. يعمل بالكامل في متصفحك.",
    "keywordsAr": [
      "اختبار regex",
      "تعبير نمطي",
      "regex عربي",
      "اختبار regular expression"
    ]
  },
  {
    "slug": "jwt-decoder",
    "category": "dev",
    "icon": "FileKey",
    "title": "JWT Decoder",
    "description": "Decode and inspect JSON Web Tokens. View header, payload, and signature instantly in your browser. No data leaves your device.",
    "keywords": [
      "jwt decoder",
      "decode jwt",
      "jwt parser",
      "json web token decoder"
    ],
    "titleAr": "فك تشفير JWT",
    "descriptionAr": "فك وتحليل رموز JWT. اعرض الـ header والـ payload والتوقيع فوراً في متصفحك. لا تغادر بياناتك جهازك.",
    "keywordsAr": [
      "فك تشفير jwt",
      "decode jwt",
      "محلل jwt",
      "json web token عربي"
    ]
  },
  {
    "slug": "csv-json-converter",
    "category": "dev",
    "icon": "Table2",
    "title": "CSV ↔ JSON Converter",
    "description": "Convert CSV to JSON and JSON to CSV instantly in your browser. Paste data or upload a file. Nothing is uploaded to a server.",
    "keywords": [
      "csv to json",
      "json to csv",
      "csv json converter",
      "convert csv"
    ],
    "titleAr": "محوّل CSV ↔ JSON",
    "descriptionAr": "حوّل CSV إلى JSON و JSON إلى CSV فوراً في متصفحك. الصق البيانات أو ارفع ملفاً. لا شيء يُرفع إلى أي خادم.",
    "keywordsAr": [
      "تحويل csv الى json",
      "json الى csv",
      "محول csv",
      "csv json عربي"
    ]
  },
  {
    "slug": "json-to-typescript",
    "category": "dev",
    "icon": "Braces",
    "title": "JSON to TypeScript",
    "description": "Convert JSON objects to TypeScript interfaces automatically. Nested objects become named interfaces.",
    "keywords": [
      "json to typescript",
      "json to interface",
      "typescript generator",
      "json to ts"
    ],
    "titleAr": "JSON إلى TypeScript",
    "descriptionAr": "حوّل كائنات JSON إلى واجهات TypeScript تلقائياً. الكائنات المتداخلة تصبح واجهات مسماة.",
    "keywordsAr": [
      "json الى typescript",
      "json الى interface",
      "مولد typescript",
      "json to ts"
    ],
    "isNew": true
  },
  {
    "slug": "url-encoder-decoder",
    "category": "dev",
    "icon": "Link",
    "title": "URL Encoder / Decoder",
    "description": "Encode or decode URL components with encodeURIComponent and decodeURIComponent.",
    "keywords": [
      "url encoder",
      "url decoder",
      "percent encode",
      "uri encode decode"
    ],
    "titleAr": "مُرمّز / مُفكّك URL",
    "descriptionAr": "رمّز أو فكّ ترميز مكوّنات URL باستخدام encodeURIComponent.",
    "keywordsAr": [
      "ترميز url",
      "فك ترميز url",
      "percent encode",
      "uri encode"
    ],
    "isNew": true
  },
  {
    "slug": "css-minifier",
    "category": "dev",
    "icon": "Minimize2",
    "title": "CSS Minifier & Formatter",
    "description": "Minify or beautify CSS. Remove comments and whitespace for production or readable output.",
    "keywords": [
      "css minifier",
      "css formatter",
      "minify css",
      "beautify css"
    ],
    "titleAr": "ضاغط ومُنسّق CSS",
    "descriptionAr": "اضغط أو جمّل CSS. أزل التعليقات والمسافات للإنتاج أو للقراءة.",
    "keywordsAr": [
      "ضاغط css",
      "تنسيق css",
      "minify css",
      "تجميل css"
    ],
    "isNew": true
  },
  {
    "slug": "js-minifier",
    "category": "dev",
    "icon": "Code",
    "title": "JavaScript Minifier",
    "description": "Minify JavaScript with Terser in your browser. Compress and mangle for smaller bundles.",
    "keywords": [
      "javascript minifier",
      "js minify",
      "terser online",
      "compress javascript"
    ],
    "titleAr": "ضاغط JavaScript",
    "descriptionAr": "اضغط JavaScript باستخدام Terser في متصفحك. ضغط وتشويش للحزم الأصغر.",
    "keywordsAr": [
      "ضاغط javascript",
      "minify js",
      "terser",
      "ضغط جافاسكربت"
    ],
    "isNew": true
  },
  {
    "slug": "xml-formatter",
    "category": "dev",
    "icon": "FileCode",
    "title": "XML Formatter",
    "description": "Format or minify XML markup. Pretty-print with indentation or compress for transport.",
    "keywords": [
      "xml formatter",
      "xml beautifier",
      "xml minify",
      "pretty print xml"
    ],
    "titleAr": "مُنسّق XML",
    "descriptionAr": "نسّق أو اضغط XML. طباعة جميلة بمسافات بادئة أو ضغط للنقل.",
    "keywordsAr": [
      "منسق xml",
      "تنسيق xml",
      "ضغط xml",
      "pretty print xml"
    ],
    "isNew": true
  },
  {
    "slug": "sql-formatter",
    "category": "dev",
    "icon": "Table2",
    "title": "SQL Formatter",
    "description": "Format SQL queries with proper indentation. Supports standard SQL syntax.",
    "keywords": [
      "sql formatter",
      "sql beautifier",
      "format sql",
      "pretty print sql"
    ],
    "titleAr": "مُنسّق SQL",
    "descriptionAr": "نسّق استعلامات SQL بمسافات بادئة صحيحة. يدعم SQL القياسي.",
    "keywordsAr": [
      "منسق sql",
      "تنسيق sql",
      "format sql",
      "تجميل sql"
    ],
    "isNew": true
  },
  {
    "slug": "gradient-generator",
    "category": "dev",
    "icon": "Blend",
    "title": "CSS Gradient Generator",
    "description": "Create linear and radial CSS gradients with a live preview and copy-ready code.",
    "keywords": [
      "gradient generator",
      "css gradient",
      "linear gradient",
      "radial gradient",
      "color gradient"
    ],
    "titleAr": "مولّد تدرجات CSS",
    "descriptionAr": "أنشئ تدرجات CSS خطية ودائرية مع معاينة مباشرة وكود جاهز للنسخ.",
    "keywordsAr": [
      "مولّد التدرجات",
      "تدرج css",
      "تدرج خطي",
      "تدرج دائري",
      "تدرج الألوان"
    ]
  },
  {
    "slug": "box-shadow-generator",
    "category": "dev",
    "icon": "Box",
    "title": "Box Shadow Generator",
    "description": "Design CSS box shadows with live preview and copy ready-to-use code.",
    "keywords": [
      "box shadow generator",
      "css shadow generator",
      "drop shadow css"
    ],
    "titleAr": "مولّد ظل CSS",
    "descriptionAr": "صمّم ظلال box-shadow بمعاينة حية وانسخ الكود مباشرة.",
    "keywordsAr": [
      "مولد ظل css",
      "box shadow",
      "ظل عنصر css"
    ]
  },
  {
    "slug": "glassmorphism-generator",
    "category": "dev",
    "icon": "Sparkles",
    "title": "Glassmorphism Generator",
    "description": "Design frosted-glass CSS effects with live preview. Copy blur, border, and background code.",
    "keywords": [
      "glassmorphism generator",
      "glass effect css",
      "frosted glass css",
      "glassmorphism css"
    ],
    "titleAr": "مولّد زجاجي CSS",
    "descriptionAr": "صمّم تأثير زجاجي ضبابي بمعاينة حية وانسخ كود CSS.",
    "keywordsAr": [
      "مولد زجاجي css",
      "glassmorphism",
      "تأثير زجاجي",
      "خلفية ضبابية"
    ]
  },
  {
    "slug": "svg-pattern-generator",
    "category": "dev",
    "icon": "Shapes",
    "title": "SVG Pattern Generator",
    "description": "Create repeating SVG background patterns and copy the CSS code.",
    "keywords": [
      "svg pattern generator",
      "css background pattern",
      "repeating pattern svg"
    ],
    "titleAr": "مولّد باترن SVG",
    "descriptionAr": "أنشئ أنماط خلفية SVG متكررة وانسخ كود CSS جاهز.",
    "keywordsAr": [
      "مولد باترن svg",
      "نمط خلفية css",
      "باترن متكرر"
    ]
  },
  {
    "slug": "og-image-generator",
    "category": "dev",
    "icon": "Share2",
    "title": "Open Graph Image Generator",
    "description": "Create 1200×630 OG images for social sharing with custom title and colors.",
    "keywords": [
      "open graph image generator",
      "og image maker",
      "social preview image",
      "og card generator"
    ],
    "titleAr": "مولّد صورة OG",
    "descriptionAr": "أنشئ صور Open Graph 1200×630 للمشاركة على الشبكات الاجتماعية.",
    "keywordsAr": [
      "مولد صورة og",
      "صورة معاينة روابط",
      "open graph",
      "صورة سوشيال"
    ]
  },
  {
    "slug": "favicon-generator",
    "category": "dev",
    "icon": "AppWindow",
    "title": "Favicon Generator",
    "description": "Generate favicon PNGs in multiple sizes from one image and download as ZIP.",
    "keywords": [
      "favicon generator",
      "favicon maker",
      "icon generator",
      "site icon generator"
    ],
    "titleAr": "مولّد فافيكون",
    "descriptionAr": "ولّد أيقونات PNG بأحجام متعددة من صورة واحدة ونزّلها كملف ZIP.",
    "keywordsAr": [
      "مولد فافيكون",
      "صانع أيقونة الموقع",
      "أيقونة متصفح"
    ]
  },
  {
    "slug": "meta-tag-generator",
    "category": "dev",
    "icon": "Tag",
    "title": "Meta Tag Generator",
    "description": "Generate HTML meta, Open Graph, and Twitter Card tags from title, description, URL, and image.",
    "keywords": [
      "meta tag generator",
      "og tags",
      "open graph generator",
      "seo meta tags"
    ],
    "titleAr": "مولّد وسوم Meta",
    "descriptionAr": "ولّد وسوم HTML meta و Open Graph و Twitter Card من العنوان والوصف والرابط والصورة.",
    "keywordsAr": [
      "مولد meta tags",
      "وسوم og",
      "open graph",
      "وسوم seo"
    ],
    "isNew": true
  },
  {
    "slug": "interaction-fx",
    "category": "dev",
    "icon": "MousePointer",
    "title": "Click Ripple Effect Generator",
    "description": "Preview material-style ripple clicks and export CSS + JS using Pointer Events.",
    "keywords": [
      "click ripple effect",
      "ripple animation css",
      "material ripple",
      "button click effect"
    ],
    "titleAr": "مولّد تأثيرات النقر",
    "descriptionAr": "عاين تأثير ripple وصدّر CSS وJS يعمل باللمس والماوس.",
    "keywordsAr": [
      "مولد تأثيرات النقر",
      "تأثير ripple",
      "تأثير ضغطة",
      "انيميشن نقر"
    ]
  },
  {
    "slug": "htaccess-redirect-generator",
    "category": "dev",
    "icon": "ArrowLeftRight",
    "title": ".htaccess Redirect Generator",
    "description": "Generate Apache mod_rewrite 301 or 302 redirect rules for .htaccess files.",
    "keywords": [
      "htaccess redirect",
      "301 redirect generator",
      "apache rewrite rule",
      "htaccess generator"
    ],
    "titleAr": "مولّد تحويل .htaccess",
    "descriptionAr": "ولّد قواعد تحويل Apache mod_rewrite 301 أو 302 لملف .htaccess.",
    "keywordsAr": [
      "htaccess redirect",
      "تحويل 301",
      "apache rewrite",
      "مولد htaccess"
    ],
    "isNew": true
  },
  {
    "slug": "cron-expression-parser",
    "category": "dev",
    "icon": "Timer",
    "title": "Cron Expression Parser",
    "description": "Parse standard 5-field cron expressions into human-readable English descriptions.",
    "keywords": [
      "cron parser",
      "cron expression",
      "cron to english",
      "crontab explain"
    ],
    "titleAr": "محلّل تعبير Cron",
    "descriptionAr": "حوّل تعبيرات cron بخمسة حقول إلى وصف إنجليزي مقروء.",
    "keywordsAr": [
      "محلل cron",
      "تعبير cron",
      "crontab",
      "شرح cron"
    ],
    "isNew": true
  },
  {
    "slug": "lorem-picsum-placeholder",
    "category": "dev",
    "icon": "Image",
    "title": "Placeholder Image Generator",
    "description": "Create custom-size placeholder PNG images with dimensions text. No external API required.",
    "keywords": [
      "placeholder image",
      "lorem picsum alternative",
      "dummy image generator",
      "placeholder png"
    ],
    "titleAr": "مولّد صور Placeholder",
    "descriptionAr": "أنشئ صور PNG placeholder بأبعاد مخصصة ونص الأبعاد. بدون API خارجي.",
    "keywordsAr": [
      "صورة placeholder",
      "بديل lorem picsum",
      "صورة وهمية",
      "placeholder png"
    ],
    "isNew": true
  },
  {
    "slug": "percentage-calculator",
    "category": "calculators",
    "icon": "Percent",
    "title": "Percentage Calculator",
    "description": "Find percentages, percent of a number, and percentage increase or decrease between values.",
    "keywords": [
      "percentage calculator",
      "percent of",
      "percentage increase",
      "percentage decrease",
      "percent change"
    ],
    "titleAr": "حاسبة النسب المئوية",
    "descriptionAr": "احسب النسب المئوية ونسبة رقم من آخر والزيادة أو النقصان المئوي بين قيمتين.",
    "keywordsAr": [
      "حاسبة النسب المئوية",
      "نسبة من",
      "زيادة مئوية",
      "نقصان مئوي",
      "تغيّر النسبة"
    ]
  },
  {
    "slug": "tip-calculator",
    "category": "calculators",
    "icon": "Receipt",
    "title": "Tip Calculator",
    "description": "Calculate tip amount and split a restaurant bill evenly between any number of people.",
    "keywords": [
      "tip calculator",
      "gratuity calculator",
      "split bill",
      "restaurant tip",
      "bill splitter"
    ],
    "titleAr": "حاسبة البقشيش",
    "descriptionAr": "احسب البقشиш وقسّم الفاتورة بالتساوي بين أي عدد من الأشخاص.",
    "keywordsAr": [
      "حاسبة بقشيش",
      "تقسيم فاتورة",
      "بقشيش مطعم",
      "حاسبة gratuity"
    ],
    "isNew": true
  },
  {
    "slug": "discount-calculator",
    "category": "calculators",
    "icon": "Tag",
    "title": "Discount Calculator",
    "description": "Calculate sale price after a percentage discount and see how much you save.",
    "keywords": [
      "discount calculator",
      "sale price calculator",
      "percent off calculator",
      "price after discount"
    ],
    "titleAr": "حاسبة الخصم",
    "descriptionAr": "احسب السعر بعد الخصم كنسبة مئوية واعرف المبلغ الذي توفره.",
    "keywordsAr": [
      "حاسبة خصم",
      "سعر بعد التخفيض",
      "نسبة خصم",
      "حاسبة تخفيضات"
    ],
    "isNew": true
  },
  {
    "slug": "bmi-calculator",
    "category": "calculators",
    "icon": "Scale",
    "title": "BMI Calculator",
    "description": "Calculate your Body Mass Index from height and weight. Supports metric and imperial units.",
    "keywords": [
      "bmi calculator",
      "body mass index",
      "bmi chart",
      "weight calculator",
      "health calculator"
    ],
    "titleAr": "حاسبة مؤشر كتلة الجسم",
    "descriptionAr": "احسب مؤشر كتلة الجسم من الطول والوزن. يدعم الوحدات المترية والإمبراطورية.",
    "keywordsAr": [
      "حاسبة مؤشر كتلة الجسم",
      "bmi",
      "جدول bmi",
      "حاسبة الوزن",
      "حاسبة الصحة"
    ]
  },
  {
    "slug": "calorie-calculator",
    "category": "calculators",
    "icon": "Flame",
    "title": "Calorie Calculator",
    "description": "Estimate daily calories using the Mifflin-St Jeor equation. BMR and TDEE for maintain, lose, or gain.",
    "keywords": [
      "calorie calculator",
      "tdee calculator",
      "bmr calculator",
      "daily calories",
      "calorie deficit"
    ],
    "titleAr": "حاسبة السعرات الحرارية",
    "descriptionAr": "قدّر السعرات اليومية بمعادلة Mifflin-St Jeor. معدل الأيض الأساسي والإجمالي للحفاظ أو الخسارة أو الزيادة.",
    "keywordsAr": [
      "حاسبة السعرات",
      "حاسبة tdee",
      "حاسبة bmr",
      "السعرات اليومية",
      "عجز السعرات"
    ]
  },
  {
    "slug": "loan-calculator",
    "category": "calculators",
    "icon": "Landmark",
    "title": "Loan Calculator",
    "description": "Calculate monthly payments, total interest, and total cost for fixed-rate loans.",
    "keywords": [
      "loan calculator",
      "mortgage calculator",
      "monthly payment",
      "amortization",
      "interest calculator"
    ],
    "titleAr": "حاسبة القروض",
    "descriptionAr": "احسب الدفعات الشهرية وإجمالي الفائدة والتكلفة الإجمالية للقروض ذات الفائدة الثابتة.",
    "keywordsAr": [
      "حاسبة القروض",
      "حاسبة الرهن العقاري",
      "الدفعة الشهرية",
      "جدول السداد",
      "حاسبة الفائدة"
    ]
  },
  {
    "slug": "mortgage-calculator",
    "category": "calculators",
    "icon": "Home",
    "title": "Mortgage Calculator",
    "description": "Estimate monthly mortgage payments, total interest, and view an amortization schedule with down payment.",
    "keywords": [
      "mortgage calculator",
      "home loan calculator",
      "amortization schedule",
      "house payment calculator"
    ],
    "titleAr": "حاسبة القرض العقاري",
    "descriptionAr": "قدّر القسط الشهري للرهن العقاري وإجمالي الفائدة مع جدول سداد ودفعة أولى.",
    "keywordsAr": [
      "حاسبة رهن عقاري",
      "قرض منزل",
      "جدول سداد",
      "قسط شهري منزل"
    ],
    "isNew": true
  },
  {
    "slug": "compound-interest",
    "category": "calculators",
    "icon": "TrendingUp",
    "title": "Compound Interest Calculator",
    "description": "Project investment growth with compound interest. Choose compounding frequency and see total returns.",
    "keywords": [
      "compound interest calculator",
      "investment calculator",
      "savings growth",
      "interest calculator"
    ],
    "titleAr": "حاسبة الفائدة المركّبة",
    "descriptionAr": "توقّع نمو الاستثمار بالفائدة المركّبة. اختر تكرار المركّب واعرض العائد الإجمالي.",
    "keywordsAr": [
      "فائدة مركبة",
      "حاسبة استثمار",
      "نمو مدخرات",
      "حاسبة فائدة"
    ],
    "isNew": true
  },
  {
    "slug": "age-calculator",
    "category": "calculators",
    "icon": "Cake",
    "title": "Age Calculator",
    "description": "Calculate your exact age in years, months, and days from your birth date. See days until your next birthday.",
    "keywords": [
      "age calculator",
      "how old am i",
      "birthday calculator",
      "age in days",
      "calculate age"
    ],
    "titleAr": "حاسبة العمر",
    "descriptionAr": "احسب عمرك بالسنوات والأشهر والأيام من تاريخ ميلادك. اعرف كم يوماً متبقياً على عيد ميلادك القادم.",
    "keywordsAr": [
      "حاسبة العمر",
      "كم عمري",
      "حساب العمر",
      "عمر بالأيام",
      "تاريخ الميلاد"
    ],
    "isNew": true
  },
  {
    "slug": "date-difference",
    "category": "calculators",
    "icon": "CalendarRange",
    "title": "Date Difference Calculator",
    "description": "Find the difference between two dates in days, weeks, months, and years. Count days until or since a date.",
    "keywords": [
      "date difference",
      "days between dates",
      "days until",
      "days since",
      "date calculator"
    ],
    "titleAr": "حاسبة فرق التواريخ",
    "descriptionAr": "احسب الفرق بين تاريخين بالأيام والأسابيع والأشهر والسنوات. عد الأيام حتى أو منذ تاريخ.",
    "keywordsAr": [
      "فرق التواريخ",
      "الأيام بين تاريخين",
      "الأيام المتبقية",
      "الأيام المنقضية",
      "حاسبة التواريخ"
    ]
  },
  {
    "slug": "due-date-calculator",
    "category": "calculators",
    "icon": "CalendarHeart",
    "title": "Due Date Calculator",
    "description": "Estimate pregnancy due date from your last menstrual period and see current pregnancy week.",
    "keywords": [
      "due date calculator",
      "pregnancy due date",
      "pregnancy week",
      "lmp calculator",
      "edd calculator"
    ],
    "titleAr": "حاسبة موعد الولادة",
    "descriptionAr": "قدّر موعد الولادة من آخر دورة شهرية واعرض أسبوع الحمل الحالي.",
    "keywordsAr": [
      "حاسبة موعد الولادة",
      "موعد الولادة المتوقع",
      "أسبوع الحمل",
      "حاسبة lmp",
      "حاسبة edd"
    ]
  },
  {
    "slug": "gpa-calculator",
    "category": "calculators",
    "icon": "GraduationCap",
    "title": "GPA Calculator",
    "description": "Calculate weighted GPA on a 4.0 scale from course credits and letter grades.",
    "keywords": [
      "gpa calculator",
      "grade point average",
      "college gpa",
      "semester gpa",
      "cumulative gpa"
    ],
    "titleAr": "حاسبة المعدل التراكمي",
    "descriptionAr": "احسب المعدل التراكمي GPA على مقياس 4.0 من ساعات المواد ودرجات الحروف.",
    "keywordsAr": [
      "حاسبة gpa",
      "المعدل التراكمي",
      "معدل جامعي",
      "gpa عربي"
    ],
    "isNew": true
  },
  {
    "slug": "fuel-cost-calculator",
    "category": "calculators",
    "icon": "Fuel",
    "title": "Fuel Cost Calculator",
    "description": "Estimate fuel needed and trip cost from distance, consumption (L/100km or MPG), and fuel price.",
    "keywords": [
      "fuel cost calculator",
      "gas trip calculator",
      "fuel consumption calculator",
      "petrol cost"
    ],
    "titleAr": "حاسبة تكلفة الوقود",
    "descriptionAr": "قدّر الوقود المطلوب وتكلفة الرحلة من المسافة والاستهلاك (لتر/100كم أو MPG) وسعر الوقود.",
    "keywordsAr": [
      "تكلفة وقود",
      "حاسبة بنزين",
      "استهلاك وقود",
      "تكلفة رحلة"
    ],
    "isNew": true
  },
  {
    "slug": "aspect-ratio-calculator",
    "category": "calculators",
    "icon": "Ratio",
    "title": "Aspect Ratio Calculator",
    "description": "Find image and video aspect ratios, use presets like 16:9, and scale width or height proportionally.",
    "keywords": [
      "aspect ratio calculator",
      "16:9 calculator",
      "image ratio",
      "video aspect ratio",
      "resize proportion"
    ],
    "titleAr": "حاسبة نسبة الأبعاد",
    "descriptionAr": "احسب نسبة أبعاد الصور والفيديو، استخدم 16:9 وغيرها، وقِس العرض أو الارتفاع تناسبياً.",
    "keywordsAr": [
      "نسبة ابعاد",
      "16:9",
      "aspect ratio",
      "ابعاد صورة",
      "ابعاد فيديو"
    ],
    "isNew": true
  },
  {
    "slug": "unit-converter",
    "category": "converters",
    "icon": "Ruler",
    "title": "Unit Converter",
    "description": "Convert length, weight, area, and volume between common units instantly.",
    "keywords": [
      "unit converter",
      "length converter",
      "weight converter",
      "metric converter",
      "volume converter"
    ],
    "titleAr": "محوّل الوحدات",
    "descriptionAr": "حوّل الطول والوزن والمساحة والحجم بين الوحدات الشائعة فوراً.",
    "keywordsAr": [
      "محوّل الوحدات",
      "محوّل الطول",
      "محوّل الوزن",
      "محوّل النظام المتري",
      "محوّل الحجم"
    ]
  },
  {
    "slug": "temperature-converter",
    "category": "converters",
    "icon": "Thermometer",
    "title": "Temperature Converter",
    "description": "Convert Celsius, Fahrenheit, and Kelvin with helpful reference notes.",
    "keywords": [
      "temperature converter",
      "celsius to fahrenheit",
      "fahrenheit to celsius",
      "kelvin converter"
    ],
    "titleAr": "محوّل درجة الحرارة",
    "descriptionAr": "حوّل بين مئوية وفهرنهايت وكلفن مع ملاحظات مرجعية مفيدة.",
    "keywordsAr": [
      "تحويل درجة حرارة",
      "مئوية الى فهرنهايت",
      "فهرنهايت الى مئوية",
      "محول كلفن"
    ],
    "isNew": true
  },
  {
    "slug": "cooking-converter",
    "category": "converters",
    "icon": "ChefHat",
    "title": "Cooking Unit Converter",
    "description": "Convert cups, tablespoons, teaspoons, milliliters, and grams for recipes.",
    "keywords": [
      "cooking converter",
      "cup to ml",
      "tablespoon to ml",
      "recipe converter",
      "kitchen units"
    ],
    "titleAr": "محوّل وحدات الطبخ",
    "descriptionAr": "حوّل أكواب وملاعق وملليلترات وغرامات للوصفات.",
    "keywordsAr": [
      "تحويل كوب الى ml",
      "ملعقة طعام",
      "وحدات طبخ",
      "محول وصفات",
      "مقاييس مطبخ"
    ],
    "isNew": true
  },
  {
    "slug": "data-unit-converter",
    "category": "converters",
    "icon": "Wifi",
    "title": "Data Unit Converter",
    "description": "Convert bits, bytes, storage sizes, and network speeds (Mbps, Gbps) instantly.",
    "keywords": [
      "data unit converter",
      "bits to bytes",
      "mbps converter",
      "bandwidth converter",
      "storage units"
    ],
    "titleAr": "محوّل وحدات البيانات",
    "descriptionAr": "حوّل بين بت وبايت وأحجام التخزين وسرعات الشبكة (Mbps, Gbps) فوراً.",
    "keywordsAr": [
      "تحويل بت الى بايت",
      "محول mbps",
      "وحدات بيانات",
      "سرعة شبكة",
      "محول bandwidth"
    ],
    "isNew": true
  },
  {
    "slug": "file-size-converter",
    "category": "converters",
    "icon": "HardDrive",
    "title": "File Size Converter",
    "description": "Convert between bytes, KB, MB, GB, TB using binary (1024) or decimal (1000) bases.",
    "keywords": [
      "file size converter",
      "bytes to mb",
      "kb to gb",
      "binary file size",
      "data size"
    ],
    "titleAr": "محوّل حجم الملفات",
    "descriptionAr": "حوّل بين بايت وKB وMB وGB وTB باستخدام الأساس الثنائي (1024) أو العشري (1000).",
    "keywordsAr": [
      "تحويل حجم ملف",
      "بايت الى ميغابايت",
      "kb الى gb",
      "حجم ملف ثنائي",
      "محول بايت"
    ],
    "isNew": true
  },
  {
    "slug": "roman-numeral-converter",
    "category": "converters",
    "icon": "Languages",
    "title": "Roman Numeral Converter",
    "description": "Convert between Arabic numerals and Roman numerals (I, V, X, L, C, D, M). Supports 1–3999.",
    "keywords": [
      "roman numeral converter",
      "arabic to roman",
      "roman to number",
      "MMXXVI",
      "numerals"
    ],
    "titleAr": "محوّل الأرقام الرومانية",
    "descriptionAr": "حوّل بين الأرقام العربية والرومانية (I, V, X, L, C, D, M) للنطاق 1–3999.",
    "keywordsAr": [
      "ارقام رومانية",
      "تحويل روماني",
      "MMXXVI",
      "روماني الى عربي",
      "محول ارقام رومانية"
    ],
    "isNew": true
  },
  {
    "slug": "number-to-words",
    "category": "converters",
    "icon": "SpellCheck",
    "title": "Number to Words — Tafqit",
    "description": "Convert numbers to words in English or Arabic (tafqit). Supports large numbers up to billions.",
    "keywords": [
      "number to words",
      "tafqit",
      "تفقيط",
      "numbers in words",
      "arabic number words"
    ],
    "titleAr": "تحويل الأرقام إلى كلمات — تفقيط",
    "descriptionAr": "حوّل الأرقام إلى كلمات بالإنجليزية أو العربية (تفقيط). يدعم أعداداً كبيرة حتى المليارات.",
    "keywordsAr": [
      "تفقيط",
      "تحويل رقم الى كلمات",
      "number to words",
      "تفقيط عربي",
      "كتابة الارقام بالحروف"
    ],
    "isNew": true
  },
  {
    "slug": "hijri-gregorian-converter",
    "category": "converters",
    "icon": "Moon",
    "title": "Hijri Gregorian Converter",
    "description": "Convert dates between Hijri (Islamic) and Gregorian calendars. Fully client-side.",
    "keywords": [
      "hijri converter",
      "islamic calendar",
      "gregorian to hijri",
      "hijri to gregorian",
      "تاريخ هجري"
    ],
    "titleAr": "محوّل التاريخ الهجري والميلادي",
    "descriptionAr": "حوّل التواريخ بين التقويم الهجري الإسلامي والميلادي. يعمل بالكامل في المتصفح.",
    "keywordsAr": [
      "تحويل هجري",
      "تقويم اسلامي",
      "ميلادي الى هجري",
      "هجري الى ميلادي",
      "تاريخ هجري"
    ],
    "isNew": true
  },
  {
    "slug": "timestamp-converter",
    "category": "converters",
    "icon": "Clock",
    "title": "Timestamp Converter",
    "description": "Convert Unix timestamps to dates and back. Supports seconds and milliseconds.",
    "keywords": [
      "timestamp converter",
      "unix timestamp",
      "epoch converter",
      "date to timestamp"
    ],
    "titleAr": "محوّل الطوابع الزمنية",
    "descriptionAr": "حوّل الطوابع الزمنية Unix إلى تواريخ والعكس. يدعم الثواني والميلي ثانية.",
    "keywordsAr": [
      "محوّل الطوابع الزمنية",
      "طابع unix",
      "محوّل epoch",
      "تاريخ إلى طابع زمني"
    ]
  },
  {
    "slug": "number-base-converter",
    "category": "converters",
    "icon": "Binary",
    "title": "Number Base Converter",
    "description": "Convert numbers between binary, octal, decimal, and hexadecimal instantly in your browser.",
    "keywords": [
      "binary converter",
      "hex to decimal",
      "decimal to binary",
      "octal converter",
      "base converter"
    ],
    "titleAr": "محوّل أنظمة الأرقام",
    "descriptionAr": "حوّل الأرقام بين الثنائي والثماني والعشري والست عشري فوراً في متصفحك.",
    "keywordsAr": [
      "تحويل ثنائي",
      "hex الى decimal",
      "decimal الى binary",
      "محول انظمة ارقام"
    ],
    "isNew": true
  },
  {
    "slug": "pomodoro-timer",
    "category": "misc",
    "icon": "Timer",
    "title": "Pomodoro Timer",
    "description": "Focus timer with work and break cycles. Customizable durations, cycle counter, and sound alerts.",
    "keywords": [
      "pomodoro timer",
      "focus timer",
      "productivity timer",
      "work break timer",
      "pomodoro technique"
    ],
    "titleAr": "مؤقت بومودورو",
    "descriptionAr": "مؤقت تركيز بدورات عمل واستراحة. مدد قابلة للتخصيص وعداد الدورات وتنبيهات صوتية.",
    "keywordsAr": [
      "مؤقت بومودورو",
      "مؤقت التركيز",
      "مؤقت الإنتاجية",
      "مؤقت العمل والراحة",
      "تقنية بومودورو"
    ]
  },
  {
    "slug": "stopwatch-timer",
    "category": "misc",
    "icon": "Timer",
    "title": "Stopwatch & Countdown Timer",
    "description": "Online stopwatch with lap times and countdown timer with audio alert. Fully client-side.",
    "keywords": [
      "stopwatch online",
      "countdown timer",
      "lap timer",
      "online timer"
    ],
    "titleAr": "ساعة إيقاف وعداد تنازلي",
    "descriptionAr": "ساعة إيقاف مع لفات وتوقيت، أو عداد تنازلي مع صوت عند الانتهاء. يعمل في المتصفح.",
    "keywordsAr": [
      "ساعة ايقاف",
      "عداد تنازلي",
      "stopwatch",
      "timer online",
      "مؤقت"
    ],
    "isNew": true
  },
  {
    "slug": "random-picker",
    "category": "misc",
    "icon": "Shuffle",
    "title": "Random Picker & Number Generator",
    "description": "Pick a random name or option from a list, or generate a random number in any range.",
    "keywords": [
      "random picker",
      "random name picker",
      "random number generator",
      "wheel picker",
      "lottery picker"
    ],
    "titleAr": "منتقي عشوائي ومولّد أرقام",
    "descriptionAr": "اختر اسماً أو خياراً عشوائياً من قائمة، أو أنشئ رقماً عشوائياً ضمن نطاق.",
    "keywordsAr": [
      "منتقي عشوائي",
      "اختيار اسم عشوائي",
      "مولّد أرقام عشوائية",
      "عجلة الاختيار",
      "منتقي السحب"
    ]
  },
  {
    "slug": "typing-speed-test",
    "category": "misc",
    "icon": "Keyboard",
    "title": "Typing Speed Test",
    "description": "Measure your typing speed in WPM and accuracy with a live typing test.",
    "keywords": [
      "typing speed test",
      "wpm test",
      "typing test",
      "words per minute",
      "typing accuracy"
    ],
    "titleAr": "اختبار سرعة الكتابة",
    "descriptionAr": "قِس سرعة كتابتك بالكلمات في الدقيقة ودقة الإدخال باختبار مباشر.",
    "keywordsAr": [
      "اختبار سرعة الكتابة",
      "اختبار wpm",
      "اختبار الكتابة",
      "كلمات في الدقيقة",
      "دقة الكتابة"
    ]
  },
  {
    "slug": "signature-pad",
    "category": "misc",
    "icon": "PenLine",
    "title": "Signature Generator PNG",
    "description": "Draw a transparent signature and download as PNG for documents and forms.",
    "keywords": [
      "signature generator png",
      "draw signature online",
      "transparent signature",
      "signature pad"
    ],
    "titleAr": "مولّد توقيع شفاف",
    "descriptionAr": "ارسم توقيعاً بخلفية شفافة ونزّله PNG للمستندات والنماذج.",
    "keywordsAr": [
      "مولد توقيع شفاف",
      "توقيع png",
      "لوحة توقيع"
    ]
  },
  {
    "slug": "mp3-cutter",
    "category": "audio",
    "icon": "Scissors",
    "title": "MP3 Cutter Online",
    "description": "Cut and trim audio files in your browser. Export as MP3 or WAV — no upload required.",
    "keywords": [
      "mp3 cutter online",
      "cut mp3",
      "trim audio",
      "audio trimmer",
      "mp3 editor"
    ],
    "titleAr": "قص ملف MP3",
    "descriptionAr": "قص وتقصير ملفات الصوت في متصفحك. تصدير MP3 أو WAV دون رفع الملفات.",
    "keywordsAr": [
      "قص mp3",
      "قص ملف mp3",
      "تقصير صوت",
      "مقص صوت",
      "محرر mp3"
    ]
  },
  {
    "slug": "audio-converter",
    "category": "audio",
    "icon": "ArrowLeftRight",
    "title": "Audio Converter",
    "description": "Convert WAV to MP3 and other audio formats locally using Web Audio API.",
    "keywords": [
      "wav to mp3 converter",
      "audio converter",
      "convert wav to mp3",
      "mp3 converter online"
    ],
    "titleAr": "محوّل الصوت",
    "descriptionAr": "حوّل WAV إلى MP3 وصيغ أخرى محلياً عبر Web Audio API.",
    "keywordsAr": [
      "تحويل wav الى mp3",
      "محول صوت",
      "تحويل wav",
      "محول mp3"
    ]
  },
  {
    "slug": "audio-merger",
    "category": "audio",
    "icon": "Files",
    "title": "Audio Merger",
    "description": "Merge multiple audio files into one track. Combine clips in order and download.",
    "keywords": [
      "merge audio files",
      "combine audio",
      "join mp3 files",
      "audio joiner online"
    ],
    "titleAr": "دمج ملفات صوتية",
    "descriptionAr": "ادمج عدة ملفات صوتية في مسار واحد بالترتيب الذي تختاره.",
    "keywordsAr": [
      "دمج ملفات صوتية",
      "دمج mp3",
      "ربط ملفات صوت",
      "جمع مقاطع صوتية"
    ]
  },
  {
    "slug": "voice-recorder",
    "category": "audio",
    "icon": "Mic",
    "title": "Online Voice Recorder",
    "description": "Record voice from your microphone and download instantly. Private browser recording.",
    "keywords": [
      "online voice recorder",
      "record audio online",
      "microphone recorder",
      "voice memo online"
    ],
    "titleAr": "تسجيل صوت أونلاين",
    "descriptionAr": "سجّل صوتك من الميكروفون ونزّل التسجيل فوراً. خاص وآمن في المتصفح.",
    "keywordsAr": [
      "تسجيل صوت اونلاين",
      "مسجل صوت",
      "تسجيل ميكروفون",
      "مذكرة صوتية"
    ]
  }
] as ToolLite[];

export function getToolBySlugLite(slug: string): ToolLite | undefined {
  return toolsLite.find((t) => t.slug === slug);
}

export function getToolsByCategoryLite(category: CategoryId): ToolLite[] {
  return toolsLite.filter((t) => t.category === category);
}
