import type { CategoryId } from "./categories";
import { sortToolsByCategory } from "./tool-order";

export interface Tool {
  slug: string;
  title: string;
  description: string;
  category: CategoryId;
  icon: string;
  keywords: string[];
  isNew?: boolean;
}

const toolDefinitions: Tool[] = [
  {
    slug: "merge-pdf",
    title: "Merge PDF",
    description: "Combine multiple PDF files into one document. Drag to reorder pages.",
    category: "pdf",
    icon: "Files",
    keywords: ["merge pdf", "combine pdf", "join pdf", "pdf merger", "pdf combiner"],
  },
  {
    slug: "split-pdf",
    title: "Split PDF",
    description: "Split a PDF into separate files by page ranges or individual pages.",
    category: "pdf",
    icon: "Scissors",
    keywords: ["split pdf", "extract pdf pages", "pdf splitter", "separate pdf pages"],
  },
  {
    slug: "pdf-to-jpg",
    title: "PDF to JPG & JPG to PDF Converter",
    description:
      "Convert PDF pages to JPG images, or combine JPG/PNG/WebP images into a single PDF.",
    category: "pdf",
    icon: "ArrowLeftRight",
    keywords: [
      "pdf to jpg",
      "pdf to image",
      "convert pdf to jpeg",
      "pdf page to image",
      "jpg to pdf",
      "image to pdf",
      "png to pdf",
      "photos to pdf",
      "combine images pdf",
    ],
  },
  {
    slug: "compress-pdf",
    title: "Compress PDF",
    description: "Reduce PDF file size with lossless optimization or strong raster compression.",
    category: "pdf",
    icon: "Minimize2",
    keywords: ["compress pdf", "reduce pdf size", "shrink pdf", "pdf compressor", "optimize pdf"],
  },
  {
    slug: "compress-image",
    title: "Compress Image",
    description: "Reduce JPG and PNG file size with adjustable quality. No upload required.",
    category: "image",
    icon: "Minimize2",
    keywords: ["compress image", "reduce image size", "jpg compressor", "png compressor", "optimize image"],
  },
  {
    slug: "image-resizer",
    title: "Image Resizer",
    description: "Resize images to exact pixel dimensions with optional aspect ratio lock.",
    category: "image",
    icon: "Scaling",
    keywords: ["resize image", "image resizer", "scale image", "change image dimensions"],
  },
  {
    slug: "crop-image",
    title: "Crop Image",
    description:
      "Crop images with a rectangle, circle, or rounded frame — right in your browser.",
    category: "image",
    icon: "Crop",
    keywords: [
      "crop image",
      "image cropper",
      "trim image",
      "cut image",
      "circle crop",
      "round profile picture",
      "circular crop",
      "rounded square crop",
    ],
  },
  {
    slug: "heic-to-jpg",
    title: "HEIC to JPG Converter",
    description: "Convert iPhone HEIC photos to JPG locally. Batch convert and download as ZIP.",
    category: "image",
    icon: "ImageDown",
    keywords: ["heic to jpg", "convert heic", "iphone photo to jpg", "heic converter"],
    isNew: true,
  },
  {
    slug: "flip-image",
    title: "Flip Image",
    description: "Flip images horizontally, vertically, or both. Instant preview, keeps PNG or JPG format.",
    category: "image",
    icon: "FlipHorizontal2",
    keywords: ["flip image", "mirror image", "flip photo horizontal", "flip vertical"],
    isNew: true,
  },
  {
    slug: "blur-image",
    title: "Blur & Pixelate Image",
    description: "Draw rectangles to blur or pixelate sensitive areas before sharing. 100% local processing.",
    category: "image",
    icon: "ScanFace",
    keywords: [
      "blur part of image",
      "pixelate image",
      "pixelate region",
      "censor image",
      "hide face in photo",
      "privacy blur",
      "blur face",
    ],
    isNew: true,
  },
  {
    slug: "image-watermark",
    title: "Image Watermark",
    description: "Add draggable text watermarks with opacity, rotation, and tile mode. Export in original format.",
    category: "image",
    icon: "Droplets",
    keywords: ["image watermark", "add watermark to photo", "text watermark", "watermark maker"],
    isNew: true,
  },
  {
    slug: "image-color-picker",
    title: "Image Color Picker",
    description: "Click any pixel to get HEX, RGB, and HSL values. Copy colors with session history.",
    category: "image",
    icon: "Pipette",
    keywords: ["image color picker", "pick color from image", "eyedropper online", "hex from photo"],
    isNew: true,
  },
  {
    slug: "passport-photo",
    title: "Passport Photo Maker",
    description: "Crop to official passport sizes at 300 DPI. Export single photo or printable sheet.",
    category: "image",
    icon: "IdCard",
    keywords: ["passport photo maker", "id photo size", "2x2 photo", "35x45mm photo"],
    isNew: true,
  },
  {
    slug: "gif-maker",
    title: "GIF Maker from Images",
    description: "Combine up to 50 images into an animated GIF with frame delay and loop control.",
    category: "image",
    icon: "Film",
    keywords: ["gif maker", "images to gif", "animated gif creator", "slideshow gif"],
    isNew: true,
  },
  {
    slug: "image-converter",
    title: "Image Converter",
    description: "Convert images between PNG, JPG, and WebP formats in your browser.",
    category: "image",
    icon: "ArrowLeftRight",
    keywords: ["image converter", "png to jpg", "jpg to png", "webp converter", "convert image format"],
  },
  {
    slug: "word-counter",
    title: "Word Counter",
    description: "Count words, characters, sentences, paragraphs, and estimated reading time.",
    category: "text",
    icon: "Hash",
    keywords: ["word counter", "character count", "text counter", "reading time"],
  },
  {
    slug: "case-converter",
    title: "Case Converter",
    description: "Convert text to uppercase, lowercase, title case, camelCase, and more.",
    category: "text",
    icon: "CaseSensitive",
    keywords: ["case converter", "uppercase", "lowercase", "title case", "camelcase", "snake case"],
  },
  {
    slug: "password-generator",
    title: "Password Generator",
    description: "Create strong random passwords with customizable length and character sets.",
    category: "text",
    icon: "KeyRound",
    keywords: ["password generator", "random password", "secure password", "strong password"],
  },
  {
    slug: "markdown-to-html",
    title: "Markdown to HTML",
    description: "Convert Markdown to HTML with a live preview and copy-ready output.",
    category: "text",
    icon: "FileCode",
    keywords: ["markdown to html", "md to html", "markdown converter", "markdown preview"],
  },
  {
    slug: "lorem-ipsum-generator",
    title: "Lorem Ipsum Generator",
    description: "Generate placeholder paragraphs, sentences, or words for mockups and drafts.",
    category: "text",
    icon: "TextQuote",
    keywords: ["lorem ipsum", "placeholder text", "dummy text", "lorem generator"],
  },
  {
    slug: "text-diff-checker",
    title: "Text Diff Checker",
    description: "Compare two texts side by side with highlighted additions and deletions.",
    category: "text",
    icon: "GitCompare",
    keywords: ["text diff", "compare text", "diff checker", "text comparison"],
  },
  {
    slug: "remove-line-breaks",
    title: "Remove Line Breaks",
    description: "Clean up text by removing line breaks, extra spaces, or converting breaks to spaces.",
    category: "text",
    icon: "WrapText",
    keywords: ["remove line breaks", "delete line breaks", "clean text", "remove newlines"],
  },
  {
    slug: "word-frequency-counter",
    title: "Word Frequency Counter",
    description: "Count how often each word appears in text and sort results by frequency.",
    category: "text",
    icon: "Hash",
    keywords: ["word frequency", "word count analysis", "text frequency counter", "keyword density"],
    isNew: true,
  },
  {
    slug: "arabic-diacritics-remover",
    title: "Arabic Diacritics Remover",
    description: "Remove Arabic tashkeel (harakat) from text instantly. Fully client-side.",
    category: "text",
    icon: "SpellCheck",
    keywords: ["remove arabic diacritics", "remove tashkeel", "strip harakat", "arabic text cleaner"],
    isNew: true,
  },
  {
    slug: "line-sorter",
    title: "Line Sorter",
    description: "Sort lines alphabetically, reverse order, or randomly. Optionally remove duplicate lines.",
    category: "text",
    icon: "ArrowLeftRight",
    keywords: ["sort lines", "alphabetical sort", "remove duplicate lines", "line sorter"],
    isNew: true,
  },
  {
    slug: "text-reverser",
    title: "Text Reverser",
    description: "Reverse entire text, individual lines, or word order. Useful for puzzles and testing.",
    category: "text",
    icon: "Shuffle",
    keywords: ["reverse text", "flip text", "reverse words", "backwards text"],
    isNew: true,
  },
  {
    slug: "slug-generator",
    title: "Slug Generator",
    description: "Convert titles to clean URL slugs with lowercase letters and hyphens.",
    category: "text",
    icon: "Link",
    keywords: ["slug generator", "url slug", "permalink generator", "seo slug"],
    isNew: true,
  },
  {
    slug: "find-and-replace",
    title: "Find and Replace",
    description: "Search and replace text with optional regex support. Replace all matches at once.",
    category: "text",
    icon: "Search",
    keywords: ["find and replace", "text replace", "regex replace", "bulk replace"],
    isNew: true,
  },
  {
    slug: "whitespace-remover",
    title: "Whitespace Remover",
    description: "Trim lines, collapse extra spaces, and remove blank lines from messy text.",
    category: "text",
    icon: "WrapText",
    keywords: ["remove whitespace", "trim lines", "clean spaces", "remove blank lines"],
    isNew: true,
  },
  {
    slug: "text-to-ascii-art",
    title: "Text to ASCII Art",
    description: "Convert text to ASCII art banners using figlet fonts. Runs in your browser.",
    category: "text",
    icon: "Type",
    keywords: ["ascii art generator", "text to ascii", "figlet online", "ascii banner"],
    isNew: true,
  },
  {
    slug: "character-map",
    title: "Character Map",
    description: "Browse special Unicode characters and symbols. Click to copy any character instantly.",
    category: "text",
    icon: "Keyboard",
    keywords: ["character map", "unicode symbols", "special characters", "copy symbols"],
    isNew: true,
  },
  {
    slug: "qr-code-generator",
    title: "QR Code Generator",
    description: "Generate QR codes from text or URLs. Download as PNG or SVG.",
    category: "dev",
    icon: "QrCode",
    keywords: ["qr code generator", "qr code maker", "create qr code", "qr code download"],
  },
  {
    slug: "json-formatter",
    title: "JSON Formatter",
    description: "Format, validate, and minify JSON with clear error messages.",
    category: "dev",
    icon: "Braces",
    keywords: ["json formatter", "json beautifier", "json validator", "json minify"],
  },
  {
    slug: "base64",
    title: "Base64 Encoder / Decoder",
    description: "Encode and decode text or images to Base64. Works entirely offline.",
    category: "dev",
    icon: "Binary",
    keywords: ["base64 encoder", "base64 decoder", "base64 converter", "image to base64"],
  },
  {
    slug: "color-picker",
    title: "Color Picker",
    description: "Pick a color and convert between HEX, RGB, and HSL formats.",
    category: "dev",
    icon: "Palette",
    keywords: ["color picker", "hex to rgb", "rgb to hex", "hsl converter", "color converter"],
  },
  {
    slug: "timestamp-converter",
    title: "Timestamp Converter",
    description: "Convert Unix timestamps to dates and back. Supports seconds and milliseconds.",
    category: "converters",
    icon: "Clock",
    keywords: ["timestamp converter", "unix timestamp", "epoch converter", "date to timestamp"],
  },
  {
    slug: "hash-generator",
    title: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, and SHA-512 hashes from any text.",
    category: "dev",
    icon: "Fingerprint",
    keywords: ["hash generator", "md5 hash", "sha256", "sha512", "checksum"],
  },
  {
    slug: "jwt-decoder",
    title: "JWT Decoder",
    description:
      "Decode and inspect JSON Web Tokens. View header, payload, and signature instantly in your browser. No data leaves your device.",
    category: "dev",
    icon: "FileKey",
    keywords: ["jwt decoder", "decode jwt", "jwt parser", "json web token decoder"],
  },
  {
    slug: "csv-json-converter",
    title: "CSV ↔ JSON Converter",
    description:
      "Convert CSV to JSON and JSON to CSV instantly in your browser. Paste data or upload a file. Nothing is uploaded to a server.",
    category: "dev",
    icon: "Table2",
    keywords: ["csv to json", "json to csv", "csv json converter", "convert csv"],
  },
  {
    slug: "regex-tester",
    title: "Regex Tester",
    description:
      "Test and debug regular expressions with live highlighting. See matches and groups as you type. Runs entirely in your browser.",
    category: "dev",
    icon: "Regex",
    keywords: ["regex tester", "regular expression tester", "regex debugger", "test regex online"],
  },
  {
    slug: "bmi-calculator",
    title: "BMI Calculator",
    description: "Calculate your Body Mass Index from height and weight. Supports metric and imperial units.",
    category: "calculators",
    icon: "Scale",
    keywords: ["bmi calculator", "body mass index", "bmi chart", "weight calculator", "health calculator"],
  },
  {
    slug: "calorie-calculator",
    title: "Calorie Calculator",
    description: "Estimate daily calories using the Mifflin-St Jeor equation. BMR and TDEE for maintain, lose, or gain.",
    category: "calculators",
    icon: "Flame",
    keywords: ["calorie calculator", "tdee calculator", "bmr calculator", "daily calories", "calorie deficit"],
  },
  {
    slug: "percentage-calculator",
    title: "Percentage Calculator",
    description: "Find percentages, percent of a number, and percentage increase or decrease between values.",
    category: "calculators",
    icon: "Percent",
    keywords: ["percentage calculator", "percent of", "percentage increase", "percentage decrease", "percent change"],
  },
  {
    slug: "loan-calculator",
    title: "Loan Calculator",
    description: "Calculate monthly payments, total interest, and total cost for fixed-rate loans.",
    category: "calculators",
    icon: "Landmark",
    keywords: ["loan calculator", "mortgage calculator", "monthly payment", "amortization", "interest calculator"],
  },
  {
    slug: "due-date-calculator",
    title: "Due Date Calculator",
    description: "Estimate pregnancy due date from your last menstrual period and see current pregnancy week.",
    category: "calculators",
    icon: "CalendarHeart",
    keywords: ["due date calculator", "pregnancy due date", "pregnancy week", "lmp calculator", "edd calculator"],
  },
  {
    slug: "date-difference",
    title: "Date Difference Calculator",
    description: "Find the difference between two dates in days, weeks, months, and years. Count days until or since a date.",
    category: "calculators",
    icon: "CalendarRange",
    keywords: ["date difference", "days between dates", "days until", "days since", "date calculator"],
  },
  {
    slug: "age-calculator",
    title: "Age Calculator",
    description: "Calculate your exact age in years, months, and days from your birth date. See days until your next birthday.",
    category: "calculators",
    icon: "Cake",
    keywords: ["age calculator", "how old am i", "birthday calculator", "age in days", "calculate age"],
    isNew: true,
  },
  {
    slug: "tip-calculator",
    title: "Tip Calculator",
    description: "Calculate tip amount and split a restaurant bill evenly between any number of people.",
    category: "calculators",
    icon: "Receipt",
    keywords: ["tip calculator", "gratuity calculator", "split bill", "restaurant tip", "bill splitter"],
    isNew: true,
  },
  {
    slug: "gpa-calculator",
    title: "GPA Calculator",
    description: "Calculate weighted GPA on a 4.0 scale from course credits and letter grades.",
    category: "calculators",
    icon: "GraduationCap",
    keywords: ["gpa calculator", "grade point average", "college gpa", "semester gpa", "cumulative gpa"],
    isNew: true,
  },
  {
    slug: "compound-interest",
    title: "Compound Interest Calculator",
    description: "Project investment growth with compound interest. Choose compounding frequency and see total returns.",
    category: "calculators",
    icon: "TrendingUp",
    keywords: ["compound interest calculator", "investment calculator", "savings growth", "interest calculator"],
    isNew: true,
  },
  {
    slug: "mortgage-calculator",
    title: "Mortgage Calculator",
    description: "Estimate monthly mortgage payments, total interest, and view an amortization schedule with down payment.",
    category: "calculators",
    icon: "Home",
    keywords: ["mortgage calculator", "home loan calculator", "amortization schedule", "house payment calculator"],
    isNew: true,
  },
  {
    slug: "fuel-cost-calculator",
    title: "Fuel Cost Calculator",
    description: "Estimate fuel needed and trip cost from distance, consumption (L/100km or MPG), and fuel price.",
    category: "calculators",
    icon: "Fuel",
    keywords: ["fuel cost calculator", "gas trip calculator", "fuel consumption calculator", "petrol cost"],
    isNew: true,
  },
  {
    slug: "discount-calculator",
    title: "Discount Calculator",
    description: "Calculate sale price after a percentage discount and see how much you save.",
    category: "calculators",
    icon: "Tag",
    keywords: ["discount calculator", "sale price calculator", "percent off calculator", "price after discount"],
    isNew: true,
  },
  {
    slug: "aspect-ratio-calculator",
    title: "Aspect Ratio Calculator",
    description: "Find image and video aspect ratios, use presets like 16:9, and scale width or height proportionally.",
    category: "calculators",
    icon: "Ratio",
    keywords: ["aspect ratio calculator", "16:9 calculator", "image ratio", "video aspect ratio", "resize proportion"],
    isNew: true,
  },
  {
    slug: "number-base-converter",
    title: "Number Base Converter",
    description: "Convert numbers between binary, octal, decimal, and hexadecimal instantly in your browser.",
    category: "converters",
    icon: "Binary",
    keywords: ["binary converter", "hex to decimal", "decimal to binary", "octal converter", "base converter"],
    isNew: true,
  },
  {
    slug: "roman-numeral-converter",
    title: "Roman Numeral Converter",
    description: "Convert between Arabic numerals and Roman numerals (I, V, X, L, C, D, M). Supports 1–3999.",
    category: "converters",
    icon: "Languages",
    keywords: ["roman numeral converter", "arabic to roman", "roman to number", "MMXXVI", "numerals"],
    isNew: true,
  },
  {
    slug: "number-to-words",
    title: "Number to Words — Tafqit",
    description: "Convert numbers to words in English or Arabic (tafqit). Supports large numbers up to billions.",
    category: "converters",
    icon: "SpellCheck",
    keywords: ["number to words", "tafqit", "تفقيط", "numbers in words", "arabic number words"],
    isNew: true,
  },
  {
    slug: "file-size-converter",
    title: "File Size Converter",
    description: "Convert between bytes, KB, MB, GB, TB using binary (1024) or decimal (1000) bases.",
    category: "converters",
    icon: "HardDrive",
    keywords: ["file size converter", "bytes to mb", "kb to gb", "binary file size", "data size"],
    isNew: true,
  },
  {
    slug: "temperature-converter",
    title: "Temperature Converter",
    description: "Convert Celsius, Fahrenheit, and Kelvin with helpful reference notes.",
    category: "converters",
    icon: "Thermometer",
    keywords: ["temperature converter", "celsius to fahrenheit", "fahrenheit to celsius", "kelvin converter"],
    isNew: true,
  },
  {
    slug: "data-unit-converter",
    title: "Data Unit Converter",
    description: "Convert bits, bytes, storage sizes, and network speeds (Mbps, Gbps) instantly.",
    category: "converters",
    icon: "Wifi",
    keywords: ["data unit converter", "bits to bytes", "mbps converter", "bandwidth converter", "storage units"],
    isNew: true,
  },
  {
    slug: "cooking-converter",
    title: "Cooking Unit Converter",
    description: "Convert cups, tablespoons, teaspoons, milliliters, and grams for recipes.",
    category: "converters",
    icon: "ChefHat",
    keywords: ["cooking converter", "cup to ml", "tablespoon to ml", "recipe converter", "kitchen units"],
    isNew: true,
  },
  {
    slug: "hijri-gregorian-converter",
    title: "Hijri Gregorian Converter",
    description: "Convert dates between Hijri (Islamic) and Gregorian calendars. Fully client-side.",
    category: "converters",
    icon: "Moon",
    keywords: ["hijri converter", "islamic calendar", "gregorian to hijri", "hijri to gregorian", "تاريخ هجري"],
    isNew: true,
  },
  {
    slug: "unit-converter",
    title: "Unit Converter",
    description: "Convert length, weight, temperature, area, and volume between common units instantly.",
    category: "converters",
    icon: "Ruler",
    keywords: ["unit converter", "length converter", "weight converter", "temperature converter", "metric converter"],
  },
  {
    slug: "gradient-generator",
    title: "CSS Gradient Generator",
    description: "Create linear and radial CSS gradients with a live preview and copy-ready code.",
    category: "dev",
    icon: "Blend",
    keywords: ["gradient generator", "css gradient", "linear gradient", "radial gradient", "color gradient"],
  },
  {
    slug: "pomodoro-timer",
    title: "Pomodoro Timer",
    description: "Focus timer with work and break cycles. Customizable durations, cycle counter, and sound alerts.",
    category: "misc",
    icon: "Timer",
    keywords: ["pomodoro timer", "focus timer", "productivity timer", "work break timer", "pomodoro technique"],
  },
  {
    slug: "random-picker",
    title: "Random Picker & Number Generator",
    description: "Pick a random name or option from a list, or generate a random number in any range.",
    category: "misc",
    icon: "Shuffle",
    keywords: ["random picker", "random name picker", "random number generator", "wheel picker", "lottery picker"],
  },
  {
    slug: "typing-speed-test",
    title: "Typing Speed Test",
    description: "Measure your typing speed in WPM and accuracy with a live typing test.",
    category: "misc",
    icon: "Keyboard",
    keywords: ["typing speed test", "wpm test", "typing test", "words per minute", "typing accuracy"],
  },
  {
    slug: "online-notepad",
    title: "Online Notepad",
    description: "A simple notepad that auto-saves to your browser. Word and character count included.",
    category: "text",
    icon: "NotebookPen",
    keywords: ["online notepad", "web notepad", "notes app", "auto save notepad", "simple notepad"],
  },
  {
    slug: "mp3-cutter",
    title: "MP3 Cutter Online",
    description: "Cut and trim audio files in your browser. Export as MP3 or WAV — no upload required.",
    category: "audio",
    icon: "Scissors",
    keywords: ["mp3 cutter online", "cut mp3", "trim audio", "audio trimmer", "mp3 editor"],
  },
  {
    slug: "audio-converter",
    title: "Audio Converter",
    description: "Convert WAV to MP3 and other audio formats locally using Web Audio API.",
    category: "audio",
    icon: "ArrowLeftRight",
    keywords: ["wav to mp3 converter", "audio converter", "convert wav to mp3", "mp3 converter online"],
  },
  {
    slug: "audio-merger",
    title: "Audio Merger",
    description: "Merge multiple audio files into one track. Combine clips in order and download.",
    category: "audio",
    icon: "Files",
    keywords: ["merge audio files", "combine audio", "join mp3 files", "audio joiner online"],
  },
  {
    slug: "voice-recorder",
    title: "Online Voice Recorder",
    description: "Record voice from your microphone and download instantly. Private browser recording.",
    category: "audio",
    icon: "Mic",
    keywords: ["online voice recorder", "record audio online", "microphone recorder", "voice memo online"],
  },
  {
    slug: "image-to-text",
    title: "Image to Text — Extract Text from Images (OCR)",
    description:
      "Convert image to text for free. Extract Arabic and English text from images right in your browser. No upload, no sign-up, no limits — fully private.",
    category: "vision",
    icon: "ScanLine",
    keywords: [
      "image to text",
      "convert image to text",
      "extract text from image",
      "ocr online free",
      "arabic ocr",
      "image to text ocr",
    ],
  },
  {
    slug: "rotate-pdf",
    title: "Rotate PDF",
    description: "Rotate PDF pages 90° at a time. Preview thumbnails and rotate all pages at once.",
    category: "pdf",
    icon: "RotateCw",
    keywords: ["rotate pdf", "turn pdf pages", "pdf rotation", "rotate pdf online", "flip pdf pages"],
  },
  {
    slug: "organize-pdf",
    title: "Organize PDF",
    description: "Reorder and delete PDF pages with drag-and-drop thumbnails. Export a new document.",
    category: "pdf",
    icon: "LayoutGrid",
    keywords: ["organize pdf", "reorder pdf pages", "delete pdf pages", "arrange pdf", "pdf page editor"],
  },
  {
    slug: "extract-pages",
    title: "Extract PDF Pages",
    description: "Pull selected pages out of a PDF into a new file or separate PDFs. Click thumbnails or type page ranges.",
    category: "pdf",
    icon: "FileOutput",
    keywords: ["extract pdf pages", "pull pages from pdf", "copy pdf pages", "save pdf pages", "extract pages from pdf"],
  },
  {
    slug: "pdf-sign",
    title: "Sign PDF Online",
    description: "Draw your signature and stamp it on a PDF document. No account or upload to servers.",
    category: "pdf",
    icon: "PenLine",
    keywords: ["sign pdf online", "pdf signature", "electronic signature pdf", "e-sign pdf"],
  },
  {
    slug: "pdf-watermark",
    title: "Add Watermark to PDF",
    description: "Add a text watermark to every page of your PDF. Adjust opacity before downloading.",
    category: "pdf",
    icon: "Droplets",
    keywords: ["add watermark to pdf", "pdf watermark", "stamp pdf", "watermark pdf online"],
  },
  {
    slug: "pdf-protect",
    title: "Password Protect PDF",
    description: "Encrypt a PDF with a password. Lock your document before sharing.",
    category: "pdf",
    icon: "Lock",
    keywords: ["password protect pdf", "encrypt pdf", "lock pdf", "pdf password online"],
  },
  {
    slug: "exif-remover",
    title: "Remove EXIF Data",
    description: "Strip GPS, camera, and metadata from photos by re-exporting through canvas.",
    category: "image",
    icon: "Eraser",
    keywords: ["remove exif data", "strip metadata", "remove photo metadata", "exif remover"],
  },
  {
    slug: "og-image-generator",
    title: "Open Graph Image Generator",
    description: "Create 1200×630 OG images for social sharing with custom title and colors.",
    category: "dev",
    icon: "Share2",
    keywords: ["open graph image generator", "og image maker", "social preview image", "og card generator"],
  },
  {
    slug: "favicon-generator",
    title: "Favicon Generator",
    description: "Generate favicon PNGs in multiple sizes from one image and download as ZIP.",
    category: "dev",
    icon: "AppWindow",
    keywords: ["favicon generator", "favicon maker", "icon generator", "site icon generator"],
  },
  {
    slug: "svg-pattern-generator",
    title: "SVG Pattern Generator",
    description: "Create repeating SVG background patterns and copy the CSS code.",
    category: "dev",
    icon: "Shapes",
    keywords: ["svg pattern generator", "css background pattern", "repeating pattern svg"],
  },
  {
    slug: "box-shadow-generator",
    title: "Box Shadow Generator",
    description: "Design CSS box shadows with live preview and copy ready-to-use code.",
    category: "dev",
    icon: "Box",
    keywords: ["box shadow generator", "css shadow generator", "drop shadow css"],
  },
  {
    slug: "image-rotator",
    title: "Image Rotator",
    description: "Rotate images 90°, 180°, or 270° in your browser. Download as PNG.",
    category: "image",
    icon: "RotateCw",
    keywords: ["rotate image", "image rotator", "turn image", "rotate photo"],
    isNew: true,
  },
  {
    slug: "add-text-to-image",
    title: "Add Text to Image",
    description: "Overlay custom text on any image with size, color, and position controls. Export PNG.",
    category: "image",
    icon: "PenLine",
    keywords: ["add text to image", "text overlay", "caption image", "write on photo"],
    isNew: true,
  },
  {
    slug: "image-collage",
    title: "Image Collage Maker",
    description: "Combine 2–4 photos into a grid collage with adjustable gap. Download as one PNG.",
    category: "image",
    icon: "LayoutGrid",
    keywords: ["image collage", "photo grid", "combine photos", "collage maker online"],
    isNew: true,
  },
  {
    slug: "signature-pad",
    title: "Signature Generator PNG",
    description: "Draw a transparent signature and download as PNG for documents and forms.",
    category: "misc",
    icon: "PenLine",
    keywords: ["signature generator png", "draw signature online", "transparent signature", "signature pad"],
  },
  {
    slug: "color-palette-generator",
    title: "Color Palette Generator",
    description: "Generate complementary, analogous, and triadic color palettes from a base color.",
    category: "dev",
    icon: "Paintbrush",
    keywords: ["color palette generator", "color scheme generator", "complementary colors", "palette maker"],
  },
  {
    slug: "glassmorphism-generator",
    title: "Glassmorphism Generator",
    description: "Design frosted-glass CSS effects with live preview. Copy blur, border, and background code.",
    category: "dev",
    icon: "Sparkles",
    keywords: ["glassmorphism generator", "glass effect css", "frosted glass css", "glassmorphism css"],
  },
  {
    slug: "css-minifier",
    title: "CSS Minifier & Formatter",
    description: "Minify or beautify CSS. Remove comments and whitespace for production or readable output.",
    category: "dev",
    icon: "Minimize2",
    keywords: ["css minifier", "css formatter", "minify css", "beautify css"],
    isNew: true,
  },
  {
    slug: "js-minifier",
    title: "JavaScript Minifier",
    description: "Minify JavaScript with Terser in your browser. Compress and mangle for smaller bundles.",
    category: "dev",
    icon: "Code",
    keywords: ["javascript minifier", "js minify", "terser online", "compress javascript"],
    isNew: true,
  },
  {
    slug: "xml-formatter",
    title: "XML Formatter",
    description: "Format or minify XML markup. Pretty-print with indentation or compress for transport.",
    category: "dev",
    icon: "FileCode",
    keywords: ["xml formatter", "xml beautifier", "xml minify", "pretty print xml"],
    isNew: true,
  },
  {
    slug: "sql-formatter",
    title: "SQL Formatter",
    description: "Format SQL queries with proper indentation. Supports standard SQL syntax.",
    category: "dev",
    icon: "Table2",
    keywords: ["sql formatter", "sql beautifier", "format sql", "pretty print sql"],
    isNew: true,
  },
  {
    slug: "url-encoder-decoder",
    title: "URL Encoder / Decoder",
    description: "Encode or decode URL components with encodeURIComponent and decodeURIComponent.",
    category: "dev",
    icon: "Link",
    keywords: ["url encoder", "url decoder", "percent encode", "uri encode decode"],
    isNew: true,
  },
  {
    slug: "uuid-generator",
    title: "UUID Generator",
    description: "Generate random UUID v4 identifiers. Create 1–20 UUIDs and copy them all at once.",
    category: "dev",
    icon: "Hash",
    keywords: ["uuid generator", "generate uuid", "uuid v4", "random uuid"],
    isNew: true,
  },
  {
    slug: "cron-expression-parser",
    title: "Cron Expression Parser",
    description: "Parse standard 5-field cron expressions into human-readable English descriptions.",
    category: "dev",
    icon: "Timer",
    keywords: ["cron parser", "cron expression", "cron to english", "crontab explain"],
    isNew: true,
  },
  {
    slug: "color-code-converter",
    title: "Color Code Converter",
    description: "Convert between HEX, RGB, HSL, and HSV color formats from a single input value.",
    category: "dev",
    icon: "Palette",
    keywords: ["color converter", "hex to rgb", "rgb to hsl", "color code converter"],
    isNew: true,
  },
  {
    slug: "meta-tag-generator",
    title: "Meta Tag Generator",
    description: "Generate HTML meta, Open Graph, and Twitter Card tags from title, description, URL, and image.",
    category: "dev",
    icon: "Tag",
    keywords: ["meta tag generator", "og tags", "open graph generator", "seo meta tags"],
    isNew: true,
  },
  {
    slug: "htaccess-redirect-generator",
    title: ".htaccess Redirect Generator",
    description: "Generate Apache mod_rewrite 301 or 302 redirect rules for .htaccess files.",
    category: "dev",
    icon: "ArrowLeftRight",
    keywords: ["htaccess redirect", "301 redirect generator", "apache rewrite rule", "htaccess generator"],
    isNew: true,
  },
  {
    slug: "lorem-picsum-placeholder",
    title: "Placeholder Image Generator",
    description: "Create custom-size placeholder PNG images with dimensions text. No external API required.",
    category: "dev",
    icon: "Image",
    keywords: ["placeholder image", "lorem picsum alternative", "dummy image generator", "placeholder png"],
    isNew: true,
  },
  {
    slug: "json-to-typescript",
    title: "JSON to TypeScript",
    description: "Convert JSON objects to TypeScript interfaces automatically. Nested objects become named interfaces.",
    category: "dev",
    icon: "Braces",
    keywords: ["json to typescript", "json to interface", "typescript generator", "json to ts"],
    isNew: true,
  },
  {
    slug: "barcode-generator",
    title: "Barcode Generator",
    description: "Generate CODE128, EAN13, UPC, and CODE39 barcodes from text. Download as PNG.",
    category: "dev",
    icon: "Barcode",
    keywords: ["barcode generator", "create barcode", "code128 generator", "ean13 barcode"],
    isNew: true,
  },
  {
    slug: "stopwatch-timer",
    title: "Stopwatch & Countdown Timer",
    description: "Online stopwatch with lap times and countdown timer with audio alert. Fully client-side.",
    category: "misc",
    icon: "Timer",
    keywords: ["stopwatch online", "countdown timer", "lap timer", "online timer"],
    isNew: true,
  },
  {
    slug: "interaction-fx",
    title: "Click Ripple Effect Generator",
    description: "Preview material-style ripple clicks and export CSS + JS using Pointer Events.",
    category: "dev",
    icon: "MousePointer",
    keywords: ["click ripple effect", "ripple animation css", "material ripple", "button click effect"],
  },
];

export const tools = sortToolsByCategory(toolDefinitions);

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: CategoryId): Tool[] {
  return tools.filter((t) => t.category === category);
}

export function searchTools(query: string): Tool[] {
  const q = query.trim().toLowerCase();
  if (!q) return tools;

  return tools.filter((tool) => {
    const haystack = [
      tool.title,
      tool.description,
      tool.category,
      ...tool.keywords,
    ]
      .join(" ")
      .toLowerCase();

    const terms = q.split(/\s+/);
    return terms.every((term) => haystack.includes(term));
  });
}
